### ISSUE TITLE
Fix interactive height changing of features in config editor

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#107]
I think this has been mentioned before but...changing height of features in the config editor doesn't get applied to the layout. Changing it in the config before change load does work

Just a weird tweak issue that I know has been mentioned before but figured I'd make an issue for it

**Comment by garrettjstevens** [comment]
From what I can tell, changing the feature height doesn't re-create the layout because the layout is done only in the webworker. Since React SSR only works on the initial load of a component and not re-renders of that component, the webworker layout code doesn't get called again.

I see two potential solutions, but maybe someone else has other ideas:

- Make the layout happen as part of the normal React lifecycle. This would allow the layout to be re-created outside the webworker, but that could potentially lock up the UI while it's happening if it's expensive (basically gets rid of the benefits of the precomputed layout).

OR

- Reload the whole block when the height is changed. I guess we would have some sort of trigger that we would have to call when the height is changed, and we'd also probably have to remember to call that any other time something was done that might change the layout (e.g. if we enable sorting by start position for alignment layouts).

There might be a third option of having some sort of layout re-calculation request where the renderer can request a new layout from the worker, but I don't have a concrete idea of how that might work or if it's even possible.

**Comment by cmdcolin** [comment]
What about the fact that color callback changing works on canvas tracks? Does that go through the webworker or is it done client side?

**Comment by rbuels** [comment]
The whole block should reload when the height is changed. To accomplish
this one could put a serialization (either the value or the stringification
of the callback) of the height configuration somewhere in the renderProps
for the track.

**Comment by cmdcolin** [comment]
Note that several other configs require a re-rendering including maxHeight, fontSize for the SVG features, etc.

**Comment by garrettjstevens** [comment]
I knew there were other configs that would probably need redoing the layout, but for some reason couldn't think of them off the top of my head. I'll try to cause a reload for height first as proof-of-concept and then figure out how to extend it to other configs that need it.

**Comment by garrettjstevens** [comment]
Hmm, adding the renderer height config to the renderProps causes a re-render when the height is changed, but the layout still isn't re-calculated.

**Comment by garrettjstevens** [comment]
I'm pretty sure the problem is in GranularRectLayout, since this code can return a rectangle that was laid out previously with a different height if the height has changed. I'm still trying to figure out the best way to get GranularRectLayout to discard and re-create the bitmap when it detects the features have changed.

https://github.com/GMOD/jbrowse-components/blob/887433d2f2a1e16d2d922dfcd112964ea699f107/packages/core/util/layouts/GranularRectLayout.ts#L343-L352
