### ISSUE TITLE
UI display issues with long refnames

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1084]
Taken from https://github.com/GMOD/jbrowse-components/issues/1082

This is a tricky one because the refname is simply quite large, but it seems like something that must be addressed

- Large refname has a text collision
- The refname dropdown is capable of displaying approx 2 letters before ellipses (sort of related to an older change where we allowed the clear button)
- The locstring box also fails to show the currently displayed region, however this is tricky. The refname is simply long

I think downsizing some of the default font sizes and stuff from material UI could go some ways towards this, but I wanted to track this as an issue

**Comment by cmdcolin** [comment]
Could review things like this during our design sprint

**Comment by laceysanderson** [comment]
+1 our reference names are also quite long (e.g. Lcu.2RBY.Chr1) due to keeping them unique across assemblies. This is especially a usability concern in the drop-down where it is difficult to select the chromosome you want.
![Screen Shot 2020-07-22 at 6 40 58 PM](https://user-images.githubusercontent.com/1566301/88242634-03684500-cc4b-11ea-90a1-09e42b809f75.png)
![Screen Shot 2020-07-22 at 6 41 12 PM](https://user-images.githubusercontent.com/1566301/88242639-06fbcc00-cc4b-11ea-8297-09e1a184957c.png)

**Comment by cmdcolin** [comment]
may be fixed by #2272
