### ISSUE TITLE
SNPCoverageTrack/WiggleTrack should retry when navigating to a new region if error had been set

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1121]
Found while navigating to large region and then zooming in

Also the error text is sort of badly formatted behind the lower PileupTrack in AlignmentsTrack

**Comment by cmdcolin** [comment]
Is there any particular reason why we think it should automatically retry. If something was so bad as to set the error state on a track, say, a 404 error, why should it retry automatically?

**Comment by cmdcolin** [comment]
It almost seems to me like the behavior of the other tracks automatically clearing the error was more of the weird thing here

**Comment by peterkxie** [comment]
In pairing with colin: 
some error design issues 
- Error message for SNPCoverageTRack and other tracks of similar height would get hidden, adjust the css
- Error messages that are too long get cut off instead of wrapping
- Error messages that are too long push the 2nd error message in a block forward and sometimes just dissapears

**Comment by cmdcolin** [comment]
Here is an alternative way of looking at the issue:


We currently have block level error statuses, but should we maybe actually remove the block level error, because then we don't have some notion of a "partial track success"

This seems to make sense to me and Peter also agreed. The reload button also, anyways, always reloads the whole track.

If there was no concept of a block level error, then this issue goes away because the user would manually hit reload for both SNPCoverage and for Pileup. Currently the pileup automatically reloads when blocks change out but SNPCoverage persists the track level error status until a manual click (which does work by the way even in the case of an operation timed out, worker killed scenario)

CC @rbuels

**Comment by rbuels** [comment]
I think we probably just want to have **both** block-level errors and track-level errors.

Track-level errors would result in the track rendering none of its blocks, just a reload button and an error message for the whole track. Block-level errors would render an error message and reload button just for that block.

Reason for this is that, if JBrowse is struggling for whatever reason (there are lots of different reasons it might be struggling), and it gets most of the way through drawing a track, but one of the blocks just fails, we would really like to just redraw that block instead of throwing all the work away that it did to get to that point.

And if one is tempted to say, "well JBrowse shouldn't be struggling", that's not really realistic, because there are lots of reasons it could be struggling that are out of our control. Maybe the network connection is flaky. Maybe their computer is overheating. Maybe they have set their bp limit way high because they are trying to view some region that is really hard to view.

So, having the errors be as granular and re-tryable as possible is what we want, I think.

And, related to this specific issue of re-trying, I think if a track has track-level errors, it should just clear the error and try again to load if navigation happens.

**Comment by cmdcolin** [comment]
>Block-level errors would render an error message and reload button just for that block.

I disagree. We basically have no idea what state the track is in if one block errors out. If it's a worker kill, reloading that block puts the track into an inconsistent state. Therefore, we rerender the whole track on any error

**Comment by rbuels** [comment]
Why does the block erroring put the track in an inconsistent state?

**Comment by cmdcolin** [comment]
layout in lost in the case of a operation timed out/worker kill. and then for other types of errors, I see little benefit to block level reload

**Comment by rbuels** [comment]
I see, the blocks aren't actually independent when a track has feature layout state in the worker. You're right that it should just be a track-level error when that is the case.

Do we have any tracks right now where the blocks actually are independent? I can't actually think of any. Wiggle tracks have auto-ranging, feature tracks have layout. I guess sequence tracks are independent but that's not that important.

I'm starting to come around to removing the block-level error handling, since apparently it's seldom a good idea to use it.

**Comment by cmdcolin** [comment]
Indeed. In the particular case of this issue, the expectation was for "SNPCoverageTrack" to automatically retry on navigating somewhere with an error state. But it gets its error when it calculated stats from dynamic blocks, so it would actually be trying any backend with requests on every scroll, unless it had some smarts about when to retry.

This is slightly different than the other tracks that have the block level error, so there was an observed discrepancy, hence this issue.

**Comment by cmdcolin** [comment]
To solve the issue, we can give it the smarts on "when to retry" which seems kinda vague or we can address the issue that other tracks with their block level error state is actually needing to be made track level

**Comment by cmdcolin** [comment]
Further, if we really wanted block independence, we could serialize layout for each request. This could be a good move anyways, but pretty unrelated here

**Comment by cmdcolin** [comment]
We went over options for this issue....what to do now?

Is it getting rid of block error? Or just close for now?

**Comment by cmdcolin** [comment]
There were a couple related things @peterkxie mentioned but seem to be maybe different issues

**Comment by rbuels** [comment]
let's just close for now and maybe we'll come up with something that feels right later
