### ISSUE TITLE
support relative URLs in config.json and jbrowse-cli

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1147]
Any relative URLs in a configuration file should be interpreted as relative to the URL that the config was loaded from.

The CLI no longer has to check whether a given data file is 

Implementation sketch:

* in jbrowse-cli
  * remove checkLocation from CLI commands
  * any CLI command that needs to do symlinks or copies or moves would operate on the directory in which the config.json is
* in the jbrowse code
  * figure out where to keep information about the base URL for a config (pluginManager? rootModel?)
  * add a types.snapshotProcessor to the fileLocation config slot types that resolves relative URLs

replaces #411

**Comment by elliothershberg** [comment]
@rbuels  One thing I'm wondering as I work on this: should this be an optional mode instead of entirely switching over? I.e. in the CLI tools have a flag to use relative paths. Or is it situation where it has to be one or the other?

**Comment by cmdcolin** [comment]
@elliothershberg  just as background the main problem this issue addresses is like this

We have a way to load configs like this

http://localhost:3000/?config=test_data/volvox/config.json



Which is this config
http://localhost:3000/test_data/volvox/config.json

And the files are like this
http://localhost:3000/test_data/volvox/volvox-sorted.bam


But the test_data/volvox/config.json has to contain full paths like this
"bamLocation": {"uri": "test_data/volvox/volvox-sorted.bam"}




Since the volvox-sorted.bam is in the same folder as the config.json, it should know to fetch it from the path of wherever this config was loaded from, and the config.json should just contain

"bamLocation": {"uri": "test_data/volvox/volvox-sorted.bam"}


I think the config system does not need a mode to use another option other than --load trust which is already there, and puts whatever the user specifies in as a literal

**Comment by cmdcolin** [comment]
Made a small typo in the above comment, fixed now

**Comment by rbuels** [comment]
@elliothershberg I don't think it would be optional, unless we can think of any really important reasons to keep the old behavior.

Like Colin said, motivation for this is so config files can contain relative URLs, and the relative URLs get resolved relative to the config file instead of the page where JBrowse is running.

**Comment by elliothershberg** [comment]
Okay, this makes sense to me.

**Comment by cmdcolin** [comment]
Basically can hand edit the relative URL into a config and ignore the CLI part for now probably

**Comment by elliothershberg** [comment]
If CLI left as it is, it would always generate an incorrect config though?

**Comment by elliothershberg** [comment]
Seems like base class of CLI would need updating, mainly resolveFileLocation

**Comment by cmdcolin** [comment]
Yep that would probably need to be done also, but I think figuring out the code inside the main app will be the main issue
