### ISSUE TITLE
Side scrolling performance improvements on chrome

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#118]
Side scrolling on chrome is generally quite fast, however if you quickly side scroll then there are blank white blocks for awhile until it is able to re-render. The sequence track is slightly better than the other tracks in load time, but I think all tracks should be a bit more performant.  I have not done profiling to see what the issue is, so I am not sure the key area to target

See  attached video
[screencast-localhost-3000-2019.02.01-18-12-04.zip](https://github.com/GMOD/jbrowse-components/files/2823654/screencast-localhost-3000-2019.02.01-18-12-04.zip)

This is of course nitpicky but I think it could look smoother and would look really good if data was already loaded as you were scrolling

Note that scrolling back over areas you have already seen have this issue too so it's not necessarily like a "first time the data is loading" thing...should be in a cache already.

**Comment by rbuels** [comment]
Yeah this is because it launches so many background renders while you
scroll that it takes the worker a while to work through them.

To really solve this well, we need to be able to cancel renders that we no
longer need. And to do that nicely, we need something like cancellable
promises (AbortController etc) that are wired all the way through to the
data stores, or at least as far down as we can get them.

Launching more than one worker could reduce the severity of this, but isn’t
a real solution.

**Comment by cmdcolin** [comment]
Interesting... I feel like they're might even be more opportunities in addition to that concert but that is good to know

**Comment by cmdcolin** [comment]
One issue is that there are network requests launched for even small sideways scrolls
