### ISSUE TITLE
Warning in tests/MainThreadRpcDriver: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1277]
This warning shows up in tests on master branch (see e.g. [here](https://travis-ci.com/github/GMOD/jbrowse-components/builds/188210623)) and anytime that MainThreadRpcDriver is used:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
```

It looks like this is related to Material-UI, and the warning appears when server-side rendering is done in an environment where a DOM is detected (like when everything is done in the main thread, which we do in out tests). Further reference: https://github.com/mui-org/material-ui/issues/15798

**Comment by cmdcolin** [comment]
Was this related to the mobx-react update? Seems like a new message

**Comment by garrettjstevens** [comment]
I think it is new, but I'm not sure when it started.

**Comment by cmdcolin** [comment]
at least looking at travis-CI this appears to have started with the mobx-react update

mobx-react-merge^1 https://travis-ci.com/github/GMOD/jbrowse-components/builds/187993358
mobx-react merge https://travis-ci.com/github/GMOD/jbrowse-components/builds/188210399

**Comment by cmdcolin** [comment]
Made a question here https://github.com/mobxjs/mobx-react/issues/902

**Comment by cmdcolin** [comment]
Got an answer that pointed me to useStaticRendering(true). This is definitely a good answer. However, we turn this off in tests, and do not use it in main thread rendering

It also enables a global which seems like it would simply not be compatible with what we are trying to do

This leads me to suspect that MainThreadRendering might be a bad idea as currently implemented, or, if implemented, maybe it should not be using the SSR machinery

**Comment by cmdcolin** [comment]
Possible approach https://github.com/GMOD/jbrowse-components/pull/1283

**Comment by elliothershberg** [comment]
This still happens in MainThreadRPC. It floods the console with a lot of warnings while working on #1616 . Definitely still happening for embedded LGV.

**Comment by cmdcolin** [comment]
I think it was known that it still happens when the issue was closed but this is a good point to document issue closures. For this issue unless we rethink our strategy for mainthreadrpc it will not be fixed (we can't ssr on the main thread basically)

**Comment by cmdcolin** [comment]
See #1283 for some discussion

**Comment by teresam856** [comment]
seems like this portion of the tests could be triggering the warning https://github.com/GMOD/jbrowse-components/blob/master/products/jbrowse-web/src/tests/JBrowse.test.js#L67-L84

**Comment by cmdcolin** [comment]
@teresam856 which warning? the " Warning: useLayoutEffect does nothing on the server" is likely being triggered by a ton of places since almost all the uses of rendering will trigger it


The other warning e.g. 

```
Warning: Expected server HTML to contain a matching <%s> in <%s>.%s',                       │On branch master
        'rect',                                                                                      │Your branch is up to date with 'origin/master'.
        'svg',                                                                                       │
        '\n' +                                                       "
```

That is related to an older issue
https://github.com/GMOD/jbrowse-components/issues/1161

And it is related to clicking on a feature which that test does

**Comment by teresam856** [comment]
@cmdcolin gotcha! the only reason the warning is appearing in that portion of the test is because it is actually clicking on the feature...but you are saying it could be triggered by other portions of the codebase as well..

**Comment by cmdcolin** [comment]
but you are saying it could be triggered by other portions of the codebase as well..

if you comment out this section in config/jest/console.js

then you will get a ton of useLayoutEffect warnings when running tests

this will match also what is seen when using MainThreadRpc in the app since tests use MainThreadRpc


```
diff --git a/config/jest/console.js b/config/jest/console.js
index b2a35b0ee..c2079a4c1 100644
--- a/config/jest/console.js
+++ b/config/jest/console.js
@@ -3,12 +3,12 @@ const originalWarn = console.warn

 // this is here to silence a warning related to useStaticRendering
 // xref https://github.com/GMOD/jbrowse-components/issues/1277
-jest.spyOn(console, 'error').mockImplementation((...args) => {
-  if (typeof args[0] === 'string' && args[0].includes('useLayoutEffect')) {
-    return undefined
-  }
-  return originalError.call(console, args)
-})
+// jest.spyOn(console, 'error').mockImplementation((...args) => {
+//   if (typeof args[0] === 'string' && args[0].includes('useLayoutEffect')) {
+//     return undefined
+//   }
+//   return originalError.call(console, args)
+// })



```

The only reason we don't get those warnings in the tests right now is because of that code snippet which silences them

**Comment by teresam856** [comment]
@cmdcolin 
Gotcha! 👍

**Comment by cmdcolin** [comment]
To summarize a little better what I think was happening

The warning happens because useStaticRendering(true) ISN'T called in MainThreadRpc

This example uses useStaticRendering(true) which then makes the code not work properly (clicking the ++ button does nothing) because the mobx observers don't work, which is basically expected because the "static rendering" makes them not do anything. This example also does not produce the warning about useLayoutEffect
https://codesandbox.io/s/new-breeze-qhpof?file=/src/App.js

This example does not run useStaticRendering(true), and does work (clicking the ++ button increments count) but it gives the useLayoutEffect warning
https://codesandbox.io/s/festive-maxwell-62wxk?file=/src/App.js

The useLayoutEffect I comes from mobx-react itself


See
```
export function useQueuedForceUpdateBlock(callback) {
    // start intercepting force-update calls
    insideRender = true;
    forceUpdateQueue = [];
    try {
        var result = callback();
        // stop intercepting force-update
        insideRender = false;
        // store queue or nothing if it was empty to execute useLayoutEffect only when necessary
        var queue_1 = forceUpdateQueue.length > 0 ? forceUpdateQueue : undefined;
        // run force-update queue in useLayoutEffect
        React.useLayoutEffect(function () {
            if (queue_1) {
                queue_1.forEach(function (x) { return x(); });
            }
        }, [queue_1]);
        return result;
    }
    finally {
        insideRender = false;
    }
}
```

Note that the latest code in mobx-react does not use this function and has no trace of useLayoutEffect, and possibly also, a previous version of mobx-react created this change as noted above, so upgrading or downgrading could be an option for this.

**Comment by cmdcolin** [comment]
Upgrading mobx-react would like be a big shift to upgrade to mobx@7, mobx-state-tree@5, etc though

**Comment by cmdcolin** [comment]
This example, with mobx, mobx-react, and mobx-state-tree dependencies  version bumped has no console warnings

https://codesandbox.io/s/immutable-sky-kv97k

HOWEVER

This WILL leak memory due to the use of useStaticRendering(true) being on for the server side rendering. https://mobx-react.js.org/recipes-ssr

Whether this is ok for a temporary instance of a user session jbrowse, it might be ok, but you would not want to run a SSR without useStaticRendering(true) on in a long running node.js process on the server side because your server would eventually crash

**Comment by cmdcolin** [comment]
with a fair amount of ts ignores and stuff it is possible to upgrade our deps, and I haven't observed anything necessarily wrong with it, not a complete conversion but partial
https://github.com/GMOD/jbrowse-components/tree/mobx_upgrades

even with this it actually still warns "Uncaught Error: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`" which is surprising though

**Comment by cmdcolin** [comment]
(with the upgrade no more useLayoutEffect warnings on mainthreadrpc just for context)

**Comment by cmdcolin** [comment]
Note that the memory leak by using mainthreadrpc may not be really something that is good to ignore

We render large numbers of observer components when using SvgFeatureRendering for example (every single subfeatures is an observer)

Using #1727 does not fix this issue. Only something like #1733 can conceptually fix that e.g. skipping SSR on the main thread entirely
