### ISSUE TITLE
small improvements to add-track GUI

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1359]
* infer the track name based on the data file name
* if an associated view is set, default the assembly to the first assembly name in that view
* add an 'index' file/url chooser in the first step that can be blank

**Comment by cmdcolin** [comment]
A first pass at this was created in #1373

**Comment by cmdcolin** [comment]
there should be something in place for this now. also now warns if

- add a ftp url
- add a http url when accessed from https instance of jbrowse
- add a url without a http prefix

it does not fully "prohibit this" but just tries to block because it likely will not work

adding a paf file via the add track workflow is still awkward due to requiring multiple assemblies but now the dotplotview and linearsyntenyview import forms prompt for paf as a workaround
