### ISSUE TITLE
Add connection refresh (session connections)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1423]
Added this ALFA hub https://ftp.ncbi.nlm.nih.gov/snp/population_frequency/TrackHub/20200227123210/hub.txt

Refreshing results in an error "Error: [mobx-state-tree] Failed to resolve reference 'UCSCTrackHubConnection-hg19-1605028856742' to type 'UCSCTrackHubConnectionConfigurationSchema' (from node: /session/connectionInstances/hg19/0/configuration)"

![localhost_3000__config=test_data%2Fconfig_demo json session=local-X_YIesDs4 (1)](https://user-images.githubusercontent.com/6511937/98708967-c2a65000-234f-11eb-8d69-39c118da6a96.png)

**Comment by peterkxie** [comment]
seems like source of error is that when not in admin mode, adding a connection is not saved since you cannot edit the config. Then on refresh it is trying to read a non-existent connection and producing the error. 

After pairing with @garrettjstevens solution may be similar to sessionTracks, if not in admin mode make them create a sessionConnection to add/save the connection

**Comment by cmdcolin** [comment]
this seems reasonable. at this stage in the session-izing, we may want to consider session assemblies

**Comment by cmdcolin** [comment]
this way connections could supply a new genome assembly, or users themselves could supply them
