### ISSUE TITLE
Add support for type bigGenePred in UCSC trackhub

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1426]
The UCSC trackhub fails to connect to https://raw.githubusercontent.com/Kraus-Lab/publichubs/master/breast_cancer_lncrna_pmid_26236012/hub.txt with error

There was a problem connecting to the UCSC Track Hub "breast cancer". Please make sure you have entered a valid hub.txt file. The error that was thrown is: "Error: Unsupported track type: bigGenePred"

The bigGenePred is a subtype of bb that should be fine to load

Note that even after adding this the hub doesn't work due to CORS but would be worth adding anyways

**Comment by garrettjstevens** [comment]
It looks like some track types have been added to the trackHub spec, and bigGenePred is one of them: https://genome.ucsc.edu/goldenPath/help/trackDb/trackDbHub.html. These should probably all be added to `plugins/data-management/src/ucsc-trackhub/ucscTrackHub.js`. Also, it would probably be better for the fallthrough case in that file to use `generateUnknownTrackConf` from `@jbrowse/core/util/tracks` instead of throwing an error so that a whole hub won't fail to add due to one bad track.
