### ISSUE TITLE
assemblies from connections

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1444]
We need to support getting assemblies from connections.

For example, we should be able to point JB2 directly at a JB1 config (or maybe a whole JB1 installation) and have it mostly work (assemblies and tracks visible and viewable).

And you should be able to open a UCSC assembly hub, and use the assembly from there.

**Comment by rbuels** [comment]
might be relevant to the JB2 Apollo plugin  cc @nathandunn @garrettjstevens

**Comment by garrettjstevens** [comment]
I was thinking about this in the context of Apollo, which might use connections, still TBD, but some of the thoughts were applicable to any kind of connection as well, so I thought I'd put them here.

I was thinking that if connections could provide assemblies, they should show up in e.g. the LGV import form. It might also be good to differentiate in the import form whether an assembly is from a connection or not. One idea I had was to have a list to select from instead of a drop-down box. That way it could have more information about the assemblies. Here's a rough mock-up:

![image](https://user-images.githubusercontent.com/25592344/169095849-3e432cd4-7fa9-4fe4-8aa0-93a60b2b095f.png)

The other thing I was thinking about was that if you open an assembly from a connection, all the tracks from that connection should automatically be in the track selector, and there shouldn't be any option to close that connection in the UI. Basically it seems like the connection tracks/assemblies should act like native config.json tracks/assemblies.

What if you open a connection assembly, though, but then want to open config.json tracks in that assembly? Would you need to add a "connection" to the config.json?

**Comment by cmdcolin** [comment]
an alternatively to this that I've thought lately is that Apollo could also take over ownership of the jbrowse instance, serving up a config.json, which is basically similar to current gen webapollo

then, desktop apollo could be a separate product

As far as making the assembly selecter UI more complex, I somewhat would prefer to keep the simple dropdown UI, as it is used in many places in the codebase now. if it is helpful to have a complex UI, it could be a popup or popover (similar to how select generates a popover). or, for a more simple approach, the source could be appended to the assembly name in the select dropdown

**Comment by garrettjstevens** [comment]
So something like this?

![image](https://user-images.githubusercontent.com/25592344/169100239-b18a94e2-f954-4986-9fd9-66451d196369.png)

**Comment by cmdcolin** [comment]
yes, could be as above (just simple text descriptions on select box), but we could also potentially create a sophisticated popover  with more features (think: HTML date inputs, they can be complicated but they often only appear once you click to make it pop up)
