### ISSUE TITLE
save and load sessions

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#146]
We need to be able to name sessions and save them in localstorage, and we need a UI for doing CRUD on saved sessions.

**Comment by rbuels** [comment]
UI operations:
* "file menu -> save session" will make a named session that will show up in the menu
* the UI will save your current complete session to localStorage every 3 seconds or so
* "file menu -> click on session name" will go back to a saved session
* when you open the browser, it will look in your localStorage for a saved last session and open that
* you can specify the name of a saved session in the URL `?session=(session name)` and it will open that session if it finds a saved session by that name

**Comment by garrettjstevens** [comment]
I've been trying to go off of Google Docs for inspiration, basically treating a session like a document. Here's some of the Docs file menu:

![image](https://user-images.githubusercontent.com/25592344/61819769-abbdb080-ae21-11e9-9766-fd3c050a1cee.png)

 I don't think we need to have a "save session" option, because sessions should just save automatically. So I think we really just need "new session", "open session", and "duplicate session" (I think I like "duplicate" better than "copy"). And then also "recent sessions". Thoughts?

**Comment by rbuels** [comment]
Sounds pretty good on the face of it, as long as people have a way to name their session. It would probably be quite intuitive because people are already familiar with the Google docs UI paradigms.

**Comment by garrettjstevens** [comment]
Oh yeah, I forgot to mention that part. I thought about having the session name in the menu bar and having it be editable.
