### ISSUE TITLE
Deploy Storybook for JBrowse React Linear Genome View

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1469]
Since the Storybook for the JBrowse React Linear Genome View can be build and deployed separately, it can act as part of the documentation for the component. Currently from the Storybook, users can see a few examples and the code that generated them. More extensive documentation is possible within Storybook.

Linking users to the deployed Storybook would take them out of our docusaurus website, so we'll need to decide on the best UI flow for that.

**Comment by cmdcolin** [comment]
One alternative is that, since storybook is kind of a heavyweight application, we just deploy a more simple demo page unless we are getting value from storybook

**Comment by cmdcolin** [comment]
I mentioned in my last comment that the storybook pipeline is fairly heavyweight. Is it something we really want to incorporate into our build? Why not something more lightweight like a create-react-app which would already have the deps installed?

**Comment by cmdcolin** [comment]
There is a maintenance aspect to this

**Comment by elliothershberg** [comment]
What do you mean by incorporating into our build? The storybook build is its own separate static build that gets hosted independently, which we would link to. I'm just about to create a public storybook link, I'll post that here once I have it. I think there are some really neat features to using it as our React component docs, so we could all maybe look at the demo link once I have it, and discuss whether it is worth having another thing that we host.

**Comment by cmdcolin** [comment]
Incorporating it into our build meaning that it is part of our continuous integration or release pipeline. That is a maintainence burden. I see making a 'create react app' website with some examples on it as simpler. Note that we had at one point almost tried to host all our docs with storybook with the docs add on and it was something I tried to spearhead but I ran into complex build system issues that eventually made me abandon it

**Comment by elliothershberg** [comment]
That makes sense. I guess I view it as a bit lower of a maintenance cost than making an additional CRA, because we are just deploying the existing storybook code we have for developing/maintaining the React LGV product. In that sense, there isn't any new code to maintain, just remembering to redeploy the docs when we update stuff.

Anyways, demo link:

http://jbrowse-storybook.s3-website-us-east-1.amazonaws.com/?path=/story/getting-started--page

@garrettjstevens @rbuels do either of you have an opinion on the maintenance question for this?

**Comment by cmdcolin** [comment]
The storybook should, IMO, be added to continuous integration, it will otherwise bitrot. That is the ongoing maintenance cost.

This documentation is now a fully separate system from docusaurus. I get kind of upset when there are so many different entry points for our docs

MDX is possible in docusaurus, we could just embed it directly in there, but alternatively, the live examples, are they really needed?


The minimal NPM readme that exists now is actually pretty good.

**Comment by cmdcolin** [comment]
Also sorry for being a little bit extra dramatic in the above comments, it's just existential anxiety about the state of the docs :)

**Comment by elliothershberg** [comment]
Ha, it’s all good! To calm your existential anxiety, I do think recent improvements have made the docs a bit easier to navigate. The recent changes to the main page do seem to provide a good overview of what we offer, but we could always work on improving the flow for people trying to find the right info.

With the storybook demo, we can all discuss the added value vs. the maintenance 👍

**Comment by rbuels** [comment]
What if we said that Storybook is going to be the canonical documentation platform for all the embedded products? So the user docs and plugin developer docs are in docusaurus, and all the embedding docs are in storybook?

**Comment by cmdcolin** [comment]
I'm not crazy about storybook as a docs platform

**Comment by cmdcolin** [comment]
I talked with @elliothershberg and I think it's good that we discussed the pros and cons, because it is a complex platform to maintain

I think this will be ok to go forward if it is added to CI and gets deployed on each build similar to our http://s3.amazonaws.com/jbrowse.org/code/jb2/master/index.html (that is my 2c, open to opinions but having the live build helps a lot IMO)
