### ISSUE TITLE
pop up a warning and remove callbacks when sharing/exporting/importing sessions

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1493]
Until we sandbox or sanitize config callbacks, we need to remove them from saved sessions when they are imported or shared.

Implementation sketch:

* when sharing or exporting a session, scan it for config callbacks and pop up a warning that they cannot be shared and will be removed, with default values used in their place. then go through and remove the config callbacks before sending the session to the share URL
* when loading a shared session from `shared-` session URLs (not localStorage or sessionStorage), scan it for config callbacks and remove them. if any were found, pop up a warning (snackbar probably) that some config callbacks were removed

**Comment by cmdcolin** [comment]
What is prompting this issue? It is true we have XSS due to this but your proposal removes functionality that I think is useful for people.  I kind of doubt a sandbox will really deliver for us


The alternative to this is we completely remove scripting callbacks entirely and use something like vega, which is doesnt use config callbacks https://vega.github.io/vega/examples/wind-vectors/

**Comment by rbuels** [comment]
Yes, it's for security.  Yes, I know it removes functionality, but I think we just need to remove it for now.

**Comment by peterkxie** [comment]
when talking with @garrettjstevens, we thought of something interesting for importing/exporting session

For exporting, don't remove callbacks since they may want to save their own custom callbacks somewhere
For importing, since you can preview the session before you confirm import, possibly detect the locations where there is a custom callback and ask if they want to use the custom callback or set to default (kind of like removing callbacks but they have more control over it). Or have some button where they can remove all custom callbacks during preview before importing.

@rbuels @cmdcolin any thoughts on the above

**Comment by cmdcolin** [comment]
Previewing a session is not really a safety mechanism. The basic proposal though is that we want to allow the user to load  callbacks from shared sessions as long as they hit an "ok" button.

**Comment by cmdcolin** [comment]
The best scenario from a security point of view is to remove eval from our codebase. Anything less than that is a mitigation

**Comment by peterkxie** [comment]
Notes for discuss in meeting:

Right now there are two modes of sending and receiving a session. There is sharing/getting a share link, and importing/exported. Need a way to protect user from getting a share link or importing a session with XSS in the callbacks. Callbacks are normally edited for custom callbacks on tracks, such as a mouseover doing something different than get feature

Currently implemented in this branch

For sharing and loading share link:
Sessions are scanned before being shared and before being loaded by Loader.tsx. Any custom callbacks are stripped and put in their default value with a warning message

For exporting and importing:
Custom callbacks are not touched on exporting, since they are saving a file outside of JBrowse. On import, the import drawer widget will pop up a message that asks user to confirm that they trust the contents of the file they are importing. Can also cancel at this point.

Things to discuss
- Are these the right methods for each
- Should we be auto-clearing callbacks for sharing
- Should importing have some way of cleaning custom callbacks
- Should sharing have the same mechanism as export/import (confirm if they trust source, no touching their session JSON)
- Other methods of implementing

**Comment by cmdcolin** [comment]
My preference after thinking about this would be to not remove callbacks, rely on user trust with maybe have a popup to confirm that they want to run the code. I don't think it makes sense to "warn them that there are callbacks and then remove them and run the session anyways". The alternative to this to me is to remove the use of eval.

Note that there are other attack surfaces if you have config.json too

We currently allow cross origin config.json

Also, we could potentially allow sessionPlugins for example, so that a non-admin user could add a plugin? This would run third party code.

Overall, I think right now it is better to rely on user-trust for receiving a share link rather than aggressively remove functionality.

**Comment by rbuels** [comment]
Per discussion in grooming just now, we won't actually remove the callbacks, but we will pop up a warning saying that the user needs to make sure that they trust the source of the link.
