### ISSUE TITLE
Reorganize session menus and options in jbrowse-web

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1526]
This is what the top-level menus look like now:

![image](https://user-images.githubusercontent.com/25592344/101197598-8f3da500-361f-11eb-95ff-23d7ed6f8191.png)

Following the discussion in #1483, we might want to break them up into more menus.

**Comment by garrettjstevens** [comment]
This is my suggestion, discussed [here](https://github.com/GMOD/jbrowse-components/pull/1483#issuecomment-731471591).

![image](https://user-images.githubusercontent.com/25592344/101197810-d7f55e00-361f-11eb-8f30-86779f39b69c.png)

**Comment by rbuels** [comment]
some points that have come up in discussing this today:

* it's useful to provide a cue to users that a session is like a word document, or a file that you are working on
* many users might not be familiar with the concept of a "session", so having a lot of menu items about sessions might not be a great idea
* localStorage may not really be reliable for storing sessions, because it gets deleted by "cleanup" programs, and clear-cache browser extensions delete it, and the chrome builtin "clear browsing data" tool also does (ctrl-shift-delete global shortcut in chrome)
* the google drive API could be a storage backend for sessions, igv.js partly does this

**Comment by rbuels** [comment]
@scottcain you've got long experience with genome browser users, do you think users know what sessions are? do you think users actually care about and use explicit session management? what if instead we only supported sharing sessions with share URLs? we might want to have a meeting to discuss paring down / curating our session management functionality

cc @ihh

**Comment by junjun-zhang** [comment]
as you suggested, @rbuels, I am attaching the propose for menu reorganization that is being discussed.

 
![image](https://user-images.githubusercontent.com/1071695/129272946-7405cd0a-66c1-4a29-9e8f-ab7d326dbde5.png)

![image](https://user-images.githubusercontent.com/1071695/129272985-d20dcb66-d608-41a6-bc55-79e871c6879c.png)

![image](https://user-images.githubusercontent.com/1071695/129273026-6257fc7b-d07a-44d2-b7d3-c7efca7eae28.png)

![image](https://user-images.githubusercontent.com/1071695/129273056-15ad6cb5-9b73-4635-8843-6cf07ffe0e18.png)

**Comment by cmdcolin** [comment]
there was a big menu redesign concurrent with desktop release. if needed can open a new issue perhaps
