### ISSUE TITLE
main thread hangs more than expected in cancer demo embedding section 

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1591]
To reproduce:

1. go to https://jbrowse.org/demos/cancer-demo-2020/#embed
2. open hg19 in the embedded lgv
3. click one of the gene names
4. while it loads, scroll up and down with your mouse wheel or touchpad
5. you will see that the scrolling hangs a bit as the processing runs

This is probably a result of using MainThreadRenderer combined with heavy BAM processing. Should be confirmed with profiling though.

Some mitigation strategies:
1. add some yielding
2. fundamental performance improvements in BAM parsing or feature rendering
3. reduce serialization overhead in MainThreadRenderer or RPC in general (like maybe #416).

**Comment by cmdcolin** [comment]
probably worth profiling the mainthreadrpc still

**Comment by cmdcolin** [comment]
this issue is a bit vague. does it mean we want webworker in embedded or just general speedups?
also the demo uses an older version of jbrowse. it may be good to wire up the cancer demo to the latest version (and keep updated) if possible. otherwise I think it should go in the conference demos with an explicit date, because our other demos are live updated

**Comment by cmdcolin** [comment]
@garrettjstevens removed serialization from main thread and any other issues may be general alignments track performance issues. #969
