### ISSUE TITLE
Add parsers to monorepo (or another monorepo)?

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#161]
After having to address an issue in some of our parsers, I feel like moving the parsers to this (or another) monorepo might be a good idea. Here are some advantages I see:
- Easier to keep track of: You can just clone one repo and get all the packages. Also, if you have a fix for the packages, it's less easy to accidentally forget one.
- Better dependency management: Everything uses the same version of babel, jest, eslint, etc., as well as using the same rules (everything would share the same eslint config, babel config, etc.)  Also much more DRY.
- Better release management: lerna provides a consistent way to release all packages.

Some cons:

- Could be confusing at first: would need to make sure the README in the root was descriptive or had good links to the READMEs in the individual packages
- Issues would all be in a single github repo instead of individual repos (could also be a pro)

Just to clarify, I don't foresee changing anything on the NPM side, so all of the packages would be exactly the same if you were installing them from NPM

Also, having parsers grouped into the jbrowse-components repo or their own repo (maybe a `gmod-utils` repo?) have different advantages. If they were in the jbrowse-components repo, you could modify a parser and your local version of jbrowse2 would automatically pull in those changes, so testing would be easy. I think I'm leaning toward creating a separate monorepo for them, though, since they are logically tied together, but not necessarily to jbrowse2, and they already almost all share a very similar architecture, so it would be a very clean monorepo. And in 15 years when jbrowse3 is rewritten again as a virtual reality genome browser :smirk:, we won't have to pull the parsers out of the jbrowse2 monorepo.

**Comment by garrettjstevens** [comment]
I fixed a couple other packages with babel problems, and I really think it would be much easier to keep our code up-to-date if all our NPM packages were somehow managed together, so that they could all have consistent code style, build, testing, and publishing processes. It might be hard to picture how they would work in a monorepo, so I created a small one to illustrate the concept: https://github.com/garrettjstevens/gmod-utils

**Comment by cmdcolin** [comment]
Seems pretty nice. My only qualm with monorepos are that I like the idea that users can just go to a github repo for cram-js and say "this is what I need" and go with it because it's pretty simple. We have already had adopters of this with igv-js and they took cram js code specifically and ran with it. I think they use a fork now. If they hit a monorepo they may or may not be able to do such a disentanglement for their own purposes.

**Comment by cmdcolin** [comment]
That said it's probably just going to be safer for us to use something like this going forward

**Comment by rbuels** [comment]
having the parsers in a monorepo would make it easier to share code from formats that are related, so that's a plus

**Comment by garrettjstevens** [comment]
Regarding this:
![image](https://user-images.githubusercontent.com/25592344/55511354-62f1aa00-562e-11e9-8822-91bae121f9c0.png)

Do we want to prioritize this since we might be getting more traffic on our modules?

**Comment by rbuels** [comment]
Yeah, that's a good point. We should decide about this now-ish.

I've been doing some thinking about this in the last day or so and I'm of the opinion that we should just leave them where they are, mostly because the work to fold them together would not buy us much, since the different parsers really don't share much code in common. That, and we would have to use a single issue tracker to track bugs in all of them, which would be kind of a pain.

So I'm just going to close this for now. Reopen if we're overlooking something.
