### ISSUE TITLE
Proposal: move less-used core plugins to external plugins

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#1656]
Some of our core plugins that were developed before the external plugin architecture was fully developed might fit better as external plugins. The purpose of moving them would be to keep the core plugins code smaller and more focused, and to not include seldom-used plugins in the JBrowse Web/Desktop default builds. In particular I was thinking of:

- Trackhub registry API plugin
- RDF plugin

Other plugins that could also perhaps be moved:

- Filtering plugin
- Lollipop plugin
- Protein plugin

**Comment by cmdcolin** [comment]
There is risk with doing that because any reference to these items in the config could become hard crashes in the UI.

The fact this would introduce hard crashes is maybe a separate issue that could be worth thinking about as we go forward

In general I'm probably fine with these externalizing some of these though

**Comment by cmdcolin** [comment]
lollipop and rdf were kept, others were removed or moved to other repos (trackhub api in particular was moved, protein and filtering deleted)
