### ISSUE TITLE
standardize on `renderer` for track config schemas

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#174]
Right now we have some track types using the config "renderer" (like FilteringTrack), some using "renderers" (like AlignmentTrack), and some using "rendering" (SequenceTrack). Should we just standardize on "renderers" and use a config like the one AlignmentTrack uses for maximum consistency and flexibility?

**Comment by rbuels** [comment]
Well, SequenceTrack as it's currently formulated is probably redundant, since a BasicTrack+DivSequenceRenderer does the same thing.  But I left it there because probably we are going to be doing some "smarter" things with the reference sequence track that will need a separate track type.

I think `.renderer` would be the best attribute name for single-renderer classes though.

**Comment by garrettjstevens** [comment]
What if someone wants to write some custom renderer and use both the default and their custom one (like how AlignmentTrack has two possible renderers). Might it not be better to assume multiple renderers are possible for everything and standardize on `.renderers`?

**Comment by rbuels** [comment]
Well, over time I think the different track types are going to specialize more and more, and we don't really know yet what that is going to look like, so it's probably a little soon for us to think about dictating that all tracks must support an array of renderers.
