### ISSUE TITLE
jbrowse-cli text indexer subcommand

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1827]
implement an indexing subcommand in jbrowse-cli that can create text indexes.

Initially, this will probably feed data to the `ixIxx` binary from the kent utils to make a trix index that we will read with the #1826 adapter

**Comment by rbuels** [comment]
CLI interface sketch

```sh
# index three local tracks into an aggregate
jbrowse text-index --tracks track1,track2,track3

# index all locally configured tracks into an aggregate, equivalent to --tracks (all_track_ids)
jbrowse text-index

# make a single-track text index for the given track
jbrowse text-index --individual --tracks my_track_id
```

Really good if all of the index drivers can estimate their runtime, and the CLI should interactively confirm "do you really want to do this" unless `--yes` flag is passed.

also, all index construction happens in temp files, and is only moved into place when the indexing is fully finished.

Initial text ingest drivers:
* gff3
* bigbed
* bed
* vcf

all input files can be optionally gzipped

Initial output drivers:
* trix with overloaded IDs, calling the `ixIxx` shell command

**Comment by rbuels** [comment]
May want to use node worker threads: https://nodejs.org/api/worker_threads.html

**Comment by rbuels** [comment]
implementation pseudocode for getting the indexing configurations in the CLI:

```js
function getIndexingConfigurations() {
  // go through all the tracks
  // instantiate their data adaptors
  // call getIndexingConfiguration() (new method we are going to write)
  // on each of them, if they have it

  return [
    {
      trackId: 'xyz123',
      indexingConfiguration: {
        indexingAdaptor: 'GFF3',
        gzipped: true,
        gff3Location: { url: 'https://example.com/somefile.gff3.gz' },
        indexAttrs: ['Name', 'ID', 'Description'],
      },
    },
    // ...
  ]
}
```

**Comment by cmdcolin** [comment]
this would make the CLI depend on nearly all plugin packages. right now jbrowse-cli doesn't even depend on jbrowse-core AFAIK, which is actually nice, because depending on jbrowse-core involves C compilers firing up to do the canvas dependency, etc.

**Comment by cmdcolin** [comment]
that is, if it actually instantiates a true instance of a "data adapter" from the plugin?

**Comment by rbuels** [comment]
only alternative to that is to hard-code a bunch of if statements. do you think that's better?

**Comment by rbuels** [comment]
like we would have to replicate the defaults in the config schemas in two places

**Comment by cmdcolin** [comment]
I would consider using bare bones approach in interpreting config.json as just JSON (our CLI currently is currently operating on that bare bones philosophy), and not even use any config schema logic. The default values like Name and ID could be hardcoded. In general things are a best effort.

To add extensibility we could consider allowing user-made "CLI hooks" or "CLI plugins"

**Comment by elliothershberg** [comment]
Talking about @rbuels about this during pairing. Recently @cmdcolin mentioned the difficulty of installing `ixixx`, making it a bit precarious as a dependency for the CLI.

Here are a few possible scenarios we thought of to mitigate this:

1. use a package manager for CLI like bioconda (with the added benefit of installing genometools more easily) https://bioconda.github.io/recipes/ucsc-ixixx/README.html and https://bioconda.github.io/recipes/genometools/README.html the biggest problem with this is that it couldn't be embedded in the electron package, since these aren't NPM dependencies
2. re-implement ixixx (in Node or Rust) @cmdcolin advocated for this option so far
3. search for if anybody has already implemented something similar
4. wrap ixixx with code to compile to WASM, distribute as its own NPM package

**Comment by cmdcolin** [comment]
Just for reference, the code for ixixx appears to be a relatively small amount of code https://github.com/ucscGenomeBrowser/kent/blob/master/src/index/ixIxx/ixIxx.c

**Comment by elliothershberg** [comment]
Nice. Seems like that heavily weights towards option 2. @rbuels and I were talking about this, what would your perception be of the value of using something like Rust vs. just Node in terms of performance? Maybe not worth it from a maintenance perspective?

**Comment by cmdcolin** [comment]
I'd go with node. i don't imagine the ixixx will really need to be super performant, it's probably like a single linear pass over a single, but probably large, ix file. writing in rust will come with complications, and not really autoamtically fix our problems.

other brainstorming:

I think if we start trying out "big data" testing of trix then the performance bottlenecks will reveal themselves. if we care about big data, a good starting point should be trying to index a dbSNP file. See https://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-common_all.vcf.gz

37 million rs IDs in the dbSNP vcf

I imagine this will reveal a number of challenges. the ix file will probably be very large since it is not compressed, and the ixx file may also get large and we know when the index file is large, that can be a bottleneck for users (e.g. a 100MB bai file is no fun).

if we cannot figure out how to handle things like this with trix, we might consider going back to on-disk hash based name store. we already have an adapter for this in jb2, and we know it is fast for the user to use (occaisionally slow for a dev to run the indexing, but really the most important thing is for end-user to feel fast to search)

**Comment by mattmorgan6** [comment]
I'm thinking Node will definitely be better than dealing with Rust (although it's a cool language). 

Testing on "big data" is highest priority rn. @cmdcolin do you have a giant gff file? that's all we are able to index at the moment.

**Comment by mattmorgan6** [comment]
Works pretty well until I hit `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` with the 37000000 :(

At least I can generate 9,000,000 lines then aggregate multiple together

**Comment by cmdcolin** [comment]
What is the size of the ix and ixx file for the resulting trix?

It could be a fluke to have a gff that big but may be worth thinking about. We may want to think about how we can do more "line by line" indexing rather than loading file into memory. In some sense, we may not even need "true gff" or "true vcf" parsers (e.g. might not need @gmod/gff or @gmod/vcf)....we can probably get by with simple string operations and line by line operations

**Comment by teresam856** [comment]
https://github.com/GMOD/jbrowse-components/blob/2ec41e7611c23be3dfbf93f6078563820b3c5e8e/products/jbrowse-cli/trix-docs.md
