### ISSUE TITLE
tabix-indexed GTF data adapter

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#1889]
Make a tabix GTF data adaptor, similar to the GFF3 one.

Some people use GTF.

**Comment by rbuels** [comment]
@bbimber says he has a lot of GTFs

**Comment by cmdcolin** [comment]
Are we sure we need this? The GTF would already need special processing to make it tabix indexed. Why not convert to GFF3 in the process?

**Comment by cmdcolin** [comment]
The tool gffread from cufflinks is easily installable individually via apt (sudo apt install gffread) or I think comes with the cufflinks software package too, and can convert gtf to gff fairly easily

https://jbrowse.org/docs/faq.html#how-do-i-convert-gtf-to-gff

**Comment by bbimber** [comment]
are you really sure you cant tabix index a GTF? the relevant columns are identical the GFF, right?

**Comment by bbimber** [comment]
Also, since i'm mentioned above: we do have a lot of GTFs, which we tend to prefer to pipeline operations as more tools use those. We keep GFFs for jbrowse/display purposes. JBrowse 1 was always better at parsing and connecting features from GFF then GTF (i.e. connecting which exons are merged into a gene and displaying it properly). 

It is not mission critical to support GTF and GFF, but given how similar GTF is to GFF it would be quite nice if jbrowse 2 handled them both the same.

**Comment by cmdcolin** [comment]
It will likely be possible, but there are a couple hurdles. For example the command we use to sort gff would not work on gtf, because I always recommend to use `gt gff3 -sortlines -tidy -retainids yourfile.gff > yourfile.sorted.gff; bgzip yourfile.sorted.gff; tabix yourfile.sorted.gff.gz;`. Therefore, we'd need a different sort command for gtf, probably can be done with GNU sort but you have to sort without the header and then concat the header back.

 And then after this we would also duplicate some paths in our codebase to support both because we probably wouldn't create a "abstraction layer over gtf/gff" so it would remain duplicated but similar.

It seemed to me, that, for gtf users, having

gffread -E yourfile.gtf -o- > yourfile.gff; gt gff3 -sortlines -tidy -retainids yourfile.gff > yourfile.sorted.gff; bgzip yourfile.sorted.gff; tabix yourfile.sorted.gff.gz;

would be easier than maintaining a separate pipeline for gtf in the code and custom tabix commands

**Comment by cmdcolin** [comment]
Note: reason that "the command we use to sort gff would not work on gtf" would be because genometools doesn't use gtf...only has the `gt gff3` subcommand

**Comment by cmdcolin** [comment]
If it is still preferable to use gtf for data integrety or integration with pipelines, we certainly can make it happen. I just wanted to ensure it is best course of action

**Comment by bbimber** [comment]
yes, GTF/GFF is a weird and awkward format. the toolset to work with them itself ideal either. 

one question: a lot of the awkwardness of GTF/GFF is that there is a lot of hierarchy (i.e. you might have one line that's a gene, one that's a transcript, then exons, all of which are grouped). people generally want the gene feature before the transcript feature, even if their start coordinates are identical. that's why tools like gt exist for sorting. for jbrowse purposes does that hierarchy matter? can a simple 'sort' command get the job done just fine? 

a note: in my experience some of the time a proper GTF/GFF sorting tool can result in a file that's not precisely coordinate ordered, which isnt tabix-compatible anyway. I dont immediately have an example, but this would occur when the hierarchy-based sorting rules conflict with straight start-position sorting.

**Comment by cmdcolin** [comment]
The hierarchy e.g. gene before transcript does not matter in jbrowse for GFF3 tabix. The gt gff3 -sortlines or most other sort commands don't need to know about this hierarchy and just output the features in whatever order, and jbrowse will reconstruct the hierarchy. Very early versions of gff3 tabix in jbrowse 1 did want hierarchy in the sort, but it doesn't need this anymore.

**Comment by bbimber** [comment]
exactly, that was my point. GNU sort would work just fine, and be identical for either GTF or GFF, right? It's a little ugly, but this kind of thing could sort the GFF/GTF while preserving headers:

```
awk '$0 ~ /^#/; { print $0 | "sort -V -k1,1 -k4,4n -k5,5n" };' test.gtf
awk '$0 ~ /^#/; { print $0 | "sort -V -k1,1 -k4,4n -k5,5n" };' test.gff

```

**Comment by cmdcolin** [comment]
Yep that should do it...nice command line fu :)

**Comment by cmdcolin** [comment]
If it is still desirable then we will go forward with it. It will involve a new parser, similar to @gmod/gff (or something more basic perhaps if just needed to get off the ground) with ability to reconstruct features properly and new GtfTabixAdapter class

It seems a fair amount of work for something that some at least say to be deprecated :) http://gmod.org/wiki/GFF2#Why_GFF2_is_harmful_to_your_health

**Comment by bbimber** [comment]
@cmdcolin I'm not necessarily saying this should move forward, but I would point out one solution might be to make the existing GFF parser more abstract and configurable. gffutils does a good job of this with a generic GTF/GFF parser, and the concept of a 'dialect' to parameterize a handful of the relevant delimiters. See:

https://github.com/daler/gffutils/blob/4b5b28e610a435af359ab1c31271deea1bae4c47/doc/source/dialect.rst

and @gmod/gff doesnt seem that complex: https://github.com/GMOD/gff-js/blob/d0443a436b11e9e8d91cf5dadd3d84ac3bdae3a1/src/util.js#L78

This would take a refactor of @mod/gff-js, but would reduce your total code in the end.

**Comment by cmdcolin** [comment]
in #2389 we found that tabix indexed GTF is not actually possible, but supplying a plaintext GTF is ok, and also providing a gzipped GTF to the plaintext GtfAdapter is ok, but tabix does not function in a way that we can work with properly. text indexing in gtf is not yet added in that pr but could maybe be added if there is interest.

(specific reason for no usage of tabix: gtf doesn't provide parent feature spans, which we use in tabix e.g. if we are zoomed into an exon, we get the coordinates of the parent gene in gff3, and we redispatch a query to get the proper gene structure to render the region around where we are looking)
