### ISSUE TITLE
Make a ViewManager

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#197]
Right now, in the interest of getting code merged, `displayedRegions` in the view is tied to all regions defined by the `AssemblyManager`. Need something in between the view model and the assembly manager (a RegionManager?) that can keep track of what regions the view is displaying, where they came from (assembly, config, regions file, user interaction, etc.), and switch among them.

**Comment by rbuels** [comment]
Maybe a ViewManager, which would be where we will put our logic for managing what views are shown, what kind of views they are, what regions they are showing, etc.

Because we are going to have a lot more kinds of views besides just LinearGenomeViews, and they will each be a little different, and will likely sometimes interact with each other.

**Comment by rbuels** [comment]
closing in favor of making lineargenomeviews able to tie themselves to assemblies
