### ISSUE TITLE
text indexing for desktop without CLI

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#2166]
We need some kind of way for the desktop to generate text indexes in the background.

Probably will need a job management system to manage the running indexing jobs.

**Comment by rbuels** [comment]
most of the UI for this will be the job status widget in #2526

**Comment by teresam856** [comment]
From grooming: 
* If an aggregate text search adapter exists in the config, check which tracks are indexed...all other tracks contained in the config will automatically be indexed if not found in the meta.json or if they do not have a per track index conf
 - create per track index 
  - we can check the meta.json
* Indexing will happen in another thread.
 -  Rpc calls (avoid clogging the thread since that is used fro track rendering)
 -  Use abort signals to cancel jobs. If a job is cancelled, do not create another one until JBrowse restarts. Keep state of jobs
 - Status callbacks to provide progress updates from the workers e.g opening bam file
* create a directory (maybe where we save the sessions) we can store the indexes generated
* we can create a queue of the jobs that we have started 
* Text background indexer class could be part of the TextSearch manager
   - watches the config and looks for tracks that are not indexed, queues those jobs

**Comment by cmdcolin** [comment]
possibly, instead of automatically indexing tracks that don't have text indexing, we could make a checkbox on the add-track widget that says it's going to index it after you add the track, and it is default checked.

only tracks that support indexing will have the checkbox


this enables

1) "junk" from getting indexed
2) giant amounts of unneeded tracks getting indexed (imagine a connection with 5000 bed.tabix files)

**Comment by teresam856** [comment]
> possibly, instead of automatically indexing tracks that don't have text indexing, we could make a checkbox on the add-track widget that says it's going to index it after you add the track, and it is default checked.
> 
> only tracks that support indexing will have the checkbox
> 
> this enables
> 
> 1. "junk" from getting indexed
> 2. giant amounts of unneeded tracks getting indexed (imagine a connection with 5000 bed.tabix files)

I agree. I think this is a good idea.

**Comment by teresam856** [comment]
From backlog grooming:
Will move the indexing logic from @core into a new module @jbrowse/text-indexing.
