### ISSUE TITLE
multi-LGV breakpoint detail view

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#224]
This is a detail view for looking at a single breakpoint.

* draw a lineargenomeview for the reference for one end of it at the top
* another lineargenomeview for the reference for the other end below that
* draw a line from one to the other

```
chr1
====|===============
     \
      \
       \
chr13   \
=========|===========

```

depends on https://github.com/GMOD/vcf-js/issues/9 (done now)

**Comment by cmdcolin** [comment]
Some notes

Breakends are pairwise. They associate two parts of the genome together. They can have  a MATEID that says what the ID of the feature is on the other side of it. They can also have an EVENT that groups multiple breakends together

**Comment by cmdcolin** [comment]
The non-synthesized reference view breakpoint lines should have little "feet" that show the directionality of the breakends. This allows you to see

chr1:1:5000 ----> chr13:5000:Infinity

Or it could be that that it this break is reversed and you have

chr1:1:5000 ----> chr13:5000:1

**Comment by cmdcolin** [comment]
* This involves creating a new view type that encapsulates 1 or more linear genome views
* We will probably just feed the view a "breakpoint to look at" and then the view will create the relevant displayed regions on the top and the bottom
* We need to have a good system for "navigating" to a specific locstring(and/or multi-locstring) in the view in order to enable this e.g. view.navigateTo(locstring). Currently options include the moveTo function on the linear genome view but this is somewhat clunky to use
* There will be react component, it needs to receive events/or look at the mobx state tree for each view, so that whenever the genome view above or below it scrolls, and it draws a breakpoint line between the views
* We need to make a sample dataset for this in vcf form, probably for volvox vs volvox genome
* If there are other breakpoints in either view, then render them in the middle area too (could involve the the vcf breakend index, or just a global download of all the breakends. see #304 )
 * If possible, make the breakend drawing actually connect to the feature inside the linear genome view. This has been shown to have been done in synteny things like the eupathdb, and it makes it clearer if it connects to the actual feature instead of just in between the views (stretch goal, possibly move into another issue)
* We're going to need a configuration system to specify receive this type of data. In the VCF breakends, it can be similar to "FromConfig" (because I imagine our particular system of "clicking on a breakend->view breakend details" as then creating this specialized view and pushing the data about that breakend onto the view. Note that this could also be a synteny data store or similar, in which case we use a special data adapter
* We're going to need to define what this feature object that the "breakend renderer" receives as it can also applies to synteny. One proposal: the breakend is an array with two objects e.g. [RegionWithAssembly,RegionWithAssembly] and then it can possibly extend to more than two elements (i.e. if you have multi-level synteny)

**Comment by cmdcolin** [comment]
Possible scenario for breakends crossing views and looping onto itself


![looping_back_breakend](https://user-images.githubusercontent.com/6511937/58725070-44006180-83ac-11e9-9c11-3ccafd5e6c96.jpg)

**Comment by garrettjstevens** [comment]
Here's a volvox VCF with breakends from the JBrowse-Rotunda integration at http://jbrowse.org/u24/:
http://jbrowse.org.s3.amazonaws.com/u24/jbrowse/sample_data/raw/volvox/volvox.dup.vcf.gz
http://jbrowse.org.s3.amazonaws.com/u24/jbrowse/sample_data/raw/volvox/volvox.dup.vcf.gz.tbi

We can use this as a start of a test data set.

**Comment by rbuels** [comment]
closing, duplicate of #475
