### ISSUE TITLE
Bug with BgzipFastaAdapter and small files

### ISSUE THREAD

**Issue by guzmanvig** [GMOD/jbrowse-components#2274]
**Describe the bug**

Compressed and indexed fasta files that are small in size throw an `Error: unable to determine size of file at {url}` error in react linear view with with `BgzipFastaAdapter`.

**To Reproduce**
The error seems to happen with any relatively small file, as an example: [small file](https://www.ncbi.nlm.nih.gov/nuccore/34577062?report=fasta)

Fasta, compressed and indexed files have the following sizes:
fasta.gz: 1.1 KB
fasta.gz.fai: 26 B
fasta.gz.gzi: 8 B

Adapter: `BgzipFastaAdapter`. Doesn't seem to happen with `IndexedFastaAdapter`

**Screenshots**

![Screenshot from 2021-08-30 17-00-38](https://user-images.githubusercontent.com/35040129/131405522-5583ce3c-9a4f-4423-9864-bcbfebf791f1.jpg)

**Version:**

jbrowse/react-linear-genome-view: 1.3.5

**Comment by cmdcolin** [comment]
This is a guess but this may be due to accessing the file over CORS (cross-origin) and the host of those files is not configured to return Content-Range via CORS

This is a little low level detail but this is because bgzip specifically uses "stat" (which uses the Content-Range header) to determine the size of the file remotely  https://github.com/GMOD/bgzf-filehandle/blob/master/src/bgzFilehandle.js#L34

In order to configure CORS correctly on your host, you might see this (this would be on the server hosting the file, not the server hosting jbrowse)
https://jbrowse.org/docs/cors.html

**Comment by cmdcolin** [comment]
There may be a possibility that we could disable this usage of stat also...could be useful if so and ease CORS configs

**Comment by guzmanvig** [comment]
Yeap, that was it! Thanks!
