### ISSUE TITLE
Reorganize web and desktop top-level menus

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#2377]
There was some good discussion based on the observations and wireframing from @junjun-zhang about desktop's top-level menus. I think it would be good to review those again now that we're approaching a final design.

### Current menus

| File | Edit | Help |
| ---- | ---- | ---- |
| ![image](https://user-images.githubusercontent.com/25592344/135860632-87cb14a3-2a1f-4e45-8f00-96560af251ca.png) | ![image](https://user-images.githubusercontent.com/25592344/135860670-7e32f615-1a73-4fe4-a2fe-06738154c55d.png) | ![image](https://user-images.githubusercontent.com/25592344/135860722-ca019a12-a04f-40c7-8882-0891bc6c279d.png) |

Example from @junjun-zhang's wireframes

![image](https://user-images.githubusercontent.com/25592344/135860875-3f869a63-c1ef-4ce5-acd2-a051cb40947c.png)

**Comment by cmdcolin** [comment]
Seems like "Add" should definitely be renamed "Add view", been a long time coming for that one.

Now, more opinionated things:

In general, I like the "File" menu. Even though it is vague, it is very idiomatic in the world of program menus, and I can describe in help text to go to "File->Add view"

This has an intuitive meaning whereas if there is a space in the menu name, or the name is more specialized, it is not as intuitive in help text I think.

I would say "Open assembly manager" could go in File also.

Then, regarding session, and particular a separate session menu, I am a little concerned again because I think the less a user has to think about session, the better.
