### ISSUE TITLE
Add NCList to jbrowse-img

### ISSUE THREAD

**Issue by scottcain** [GMOD/jbrowse-components#2491]
jbrowse-img is a terrific tool that I think will gain traction with many users. One thing that might expand that potential user base is being able to use existing JBrowse 1 NCList tracks which it currently doesn't support. Along the same lines, it would be nice to automatically detect NCList data in JBrowse desktop and not count on users knowing that's what it is and correctly select it from an impressively long list of supported data formats.

**Comment by cmdcolin** [comment]
>Along the same lines, it would be nice to automatically detect NCList data in JBrowse desktop and not count on users knowing that's what it is and correctly select it from an impressively long list of supported data formats.

good catch, this was a small bug should be fixed now (via https://github.com/GMOD/jbrowse-components/commit/452d884c02d102c10f1703595ded687c404fdaf1)

> jbrowse-img is a terrific tool that I think will gain traction with many users. One thing that might expand that potential user base is being able to use existing JBrowse 1 NCList tracks which it currently doesn't support. 

jbrowse-img doesn't currently nclist, and partly that is because the jbrowse embedded react component (which is builds on top of) doesn't support this either because it doesn't include the legacy-jbrowse plugin currently

**Comment by cmdcolin** [comment]
retitled to reflect jbrowse-img specific issue now

**Comment by cmdcolin** [comment]
probably can close as react-lgv has legacy-jbrowse now. not sure if jbrowse-img needs any additional features. no command line flag exists for nclist for jbrowse-img, but could be passed in as a config.json
