### ISSUE TITLE
Use generic-filehandle for RemoteFile

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#250]
Use`generic-filehandle`'s `RemoteFile` instead of `OpenUrl`, once https://github.com/GMOD/generic-filehandle/issues/4 is done and we can use `http-range-fetcher`

**Comment by cmdcolin** [comment]
The linked issue is done. Also generic-filehandle publishes it's types now..that was driving me crazy but was linked to https://github.com/Microsoft/TypeScript/issues/27311#issuecomment-484160104.

I note the types also because the filehandle usage should standardize on receiving the options with opts.signal rather than signal as it's own argument (we could allow AbortSignal | Options but I'd prefer centralizing on the Options argument)

**Comment by rbuels** [comment]
i did a little bit of looking at this, and I couldn't quite find a way to glue http-range-fetcher to RemoteFile, because range fetcher doesn't expose a fetch, it exposes its own fetching function format.  I ended up just expanding GloballyCachedFilehandle in rangeFetcher.js to support file urls

**Comment by cmdcolin** [comment]
I would like to have a way to make the generic-filehandle library something that is actually used by our systems if possible because otherwise it will not receive updates and become out of date. Would GloballyCachedFilehandle be something that generic-filehandle should incorporate?

**Comment by rbuels** [comment]
Actually, I think it would be possible to construct a special `fetch` callback for passing to generic-filehandle's RemoteFile that would call the http-range-fetcher if the request has a byte range on it, or just forward to tenacious fetch otherwise.

**Comment by rbuels** [comment]
Need to smooth over some weird things that tenacious-fetch does:
* it throws when a request fails, need to catch those
* has a different error object from regular fetch, need to regularize the error objects

Let's also remove the Electron special-casing from rangeFetcher for now, and if we need to do some electron special stuff let's do that via dependency injection of some weird stuff that only lives in the future jbrowse-desktop package.

**Comment by rbuels** [comment]
After today's pairing with colin I'm thinking the best course might be to make a new release of http-range-fetcher that better mimics that of `fetch`

**Comment by cmdcolin** [comment]
I think it would not be unreasonable to make it so that we access buffer directly

For example, node-fetch has Body.buffer() instead of the standard in browser Body.arrayBuffer()

generic-filehandle immediately converts from arrayBuffer to buffer anyways so we could just check for existence of this buffer method

**Comment by rbuels** [comment]
yeah, i think you're right.  https://github.com/GMOD/generic-filehandle/issues/10 tracks adding this to generic-filehandle
