### ISSUE TITLE
Async feature details

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2554]
This is at this stage just an idea, but if we made it so that requesting feature details was an async operation, it would allow for less serialization across the webworker which is known to take extra time and memory e.g. the serialization has to convert the specialized feature objects e.g. VcfFeature,BamSlightlyLazyFeature,CramSlightlyLazyFeature) to plain JSON objects which increases memory usage

This primarily would help with large data files like VCF with many samples and BAM/CRAM

The basic concept for this is that clicking on a feature would make a request to the rpc server e.g. webworker for the feature details

**Comment by bbimber** [comment]
If I could make a couple comments on our usage:
- Our mgap.ohsu.edu site uses JB2 to present a large VCF with ~40m variants, and >2K samples. The VCF has a lot of INFO annotations, so on the whole it's a lot of text to send around and parse. 
- Much of the time we dont actually need to parse all the data. One thing we've pondered is trying to make a trimmed down VCF which would drive the overview, and then perhaps try to configure the details view to use a completely different VCF which holds the full detail
- Another thing we pondered is trying to have lazier parsing of the data. This might not make all that much of a difference, since we'd still download the full data.
- We do have reasons to sometimes need full variant detail outside of the details view. For example, we color variants based on an INFO field. We also sometimes let the user filter variants based on INFO fields, or filter based on genotypes. Therefore at least in our use-case, we probably do need to have access to the full information about each variant, even in the overview level

**Comment by cmdcolin** [comment]
that is good context to have. i think it is all still in line with what the request is suggesting.


>Much of the time we dont actually need to parse all the data. One thing we've pondered is trying to make a trimmed down VCF which would drive the overview, and then perhaps try to configure the details view to use a completely different VCF which holds the full detail

this is a good idea for some cases, and it is something the phytozome team ended up doing in their instance of jbrowse 1 (serve stripped down vcf to render features, and have rich feature details panels fetched froma  rest api i believe), but it is still beneficial for us to make normal tabix vcf as fast as we can

>Another thing we pondered is trying to have lazier parsing of the data. This might not make all that much of a difference, since we'd still download the full data.

Our vcf parser object lazily parses all sample genotypes already and is reasonably fast. even put it to a benchmark here :) https://github.com/brentp/vcf-bench the main slowness comes from the conversion to json that we do.




>We do have reasons to sometimes need full variant detail outside of the details view. For example, we color variants based on an INFO field. We also sometimes let the user filter variants based on INFO fields, or filter based on genotypes. Therefore at least in our use-case, we probably do need to have access to the full information about each variant, even in the overview level

this coloring happens in the renderer which is also an rpc operation so this is still in line with this proposal.

**Comment by cmdcolin** [comment]
this issue may be difficult to properly solve this for svg feature renderers in particular.

this is because the react based svg rendering components run on both the backend (render) and frontend (hydrate, which actually rerenders) so unless you actually send the feature data over the rpc boundary via json'ifying it, it will not be able to hydrate properly

there might possibly still be an opportunity for canvas based renderers (e.g. pileuprenderer) to use async feature details but just thought i'd mention this challenge

**Comment by cmdcolin** [comment]
this was added for pileup in particular. other track/display/renderer types can incorporate as needed :)

**Comment by cmdcolin** [comment]
pileup was particularly important because it led to a large serialization overhead of many alignments features

**Comment by cmdcolin** [comment]
also, technically embedded does not suffer from serialization overheads so performance that @bbimber mentioned with VCF might arise from something else in an embedded context.
