### ISSUE TITLE
Track selector hard to find if closed

### ISSUE THREAD

**Issue by ihh** [GMOD/jbrowse-components#2717]
When the linear genome view is launched, an "Open Track Selector" button appears. If I then select a track, the "Open Track Selector" and close the track selector, it is not obvious how to get it back. I have to close all tracks and then the "Open Track Selector" button appears again. Is this the only way to do it? If so it is pretty stoopid. I have to completely close all tracks just to get another track.

I don't really see why there is a need to be able to close the track selector at all? Minimizing it works fine and is easy to undo.

**Comment by cmdcolin** [comment]
we do try to provide multiple ways to open the track selector

see screenshot

![Screenshot from 2022-02-06 07-31-57](https://user-images.githubusercontent.com/6511937/152685844-793a8e65-2816-4996-8d1f-36d988e8f24d.png) 

however, i think we do need methods to close drawer widgets. otherwise over time too many drawer widgets get built up in the 'drawer widget stack' (there are many drawer widget types and some of them you just want to close)

**Comment by ihh** [comment]
OK, I guess this does address my point, tbh I had forgotten that was even a menu there, maybe there is a choice of material-ui icons to think about; shouldn't it be three vertical dots?

I guess closing drawer widgets is a separate issue
