### ISSUE TITLE
MacOS can not open  *breakpoint split view* mode

### ISSUE THREAD

**Issue by yipukangda** [GMOD/jbrowse-components#2985]
**just download latest version of Mac desktop jbrowse and install, when try to open breakpoint split view, it returns an error massage**

Error: net::ERR_TIMED_OUT
at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
at SimpleURLLoaderWrapper.emit (node:events:390:28)

**Expected behavior**

Expect return such as showed on web document

**Screenshots**

<img width="260" alt="image" src="https://user-images.githubusercontent.com/12163499/171075177-6f242ec2-6190-46c5-a7b3-4d2e0e4a9537.png">

**Version:**

jbrowse 1.7.8
macOS Big Sur M1 chip

**Additional context**

**Comment by cmdcolin** [comment]
interesting...I don't have a M1 mac but on a older macbook it seems to be able to open breakpoint split view on my test (I tried starting a sv inspector, opening a vcf, clicking on a chord in the circular, and then the new breakpoint split view opens ok)

is there this the same thing you tried or is there a different procedure that can reproduce this?

**Comment by cmdcolin** [comment]
are you still seeing this issue?

**Comment by scottcain** [comment]
Hi @yipukangda 

I just tried the split point view in JBrowse 2 1.7.10 on an M1 Mac (MacOS 12.4) and opening a split view worked (clicking on a chord in the circular view opened a split view with no error).  Hopefully you don't need to go to Monterey to get this to work, but can you try updating your JBrowse to see if that does the trick? Since I think this is likely fixed, I'm going to close but feel free to reopen if it still doesn't work.

**Comment by yipukangda** [comment]
@scottcain Hi, I guess it may be caused by my RAM size(8G), since I tried with a 16G RAM windows pc with same data, it worked. Thanks
