### ISSUE TITLE
Embedding react view with a config.json

### ISSUE THREAD

**Issue by heavywatal** [GMOD/jbrowse-components#3061]
**Is your feature request related to a problem? Please describe.**

We can create and modify `config.json` with `@jbrowse/cli`. But it cannot be read by `@jbrowse/react-linear-genome-view`, and we have to prepare `assembly.js`, `tracks.js`, and some other codes according to [the tutorial](https://jbrowse.org/jb2/docs/tutorials/embed_linear_genome_view/01_introduction/).

**Describe the solution you'd like**

It would be nice if `@jbrowse/react-linear-genome-view` could simply read `config.json` written by `@jbrowse/cli`.
If it is too difficult in some reasons, it would be helpful if `@jbrowse/cli` provide a function to generate the required files and codes based on `config.json`.

**Describe alternatives you've considered**

Each user writes a script to extract `assembly`, `tracks`, and other information from `config.json` to generate the required files and codes for react views.

**Additional context**

**Comment by cmdcolin** [comment]
I think we may not implement this feature. I will close for now, but possibly in the future @jbrowse/react-linear-genome-view could take multiple assemblies so that it can effectively read a config.json that a user hand-fetches (as my code snippet  in https://github.com/GMOD/jbrowse-components/issues/3061#issuecomment-1170301511 does)
