### ISSUE TITLE
Unable to use 'feature' argument in jexl functions

### ISSUE THREAD

**Issue by mriedl93** [GMOD/jbrowse-components#3177]
**Describe the bug**

I'm trying to implement configuration callbacks accoding to the docs written [here](https://jbrowse.org/jb2/docs/config_guide/#configuration-callbacks).
The function described in the docs don't work for me somehow. Any function that has `feature` as argument to the function call fails,
i.e. `get(...)` fails while `log(...)` works.

**To Reproduce**

1. Use jexl expression in `config.json`
```javascript
// ...
    {
      "type": "FeatureTrack",
      "trackId": "OrganismGenome_ChromatinStatesTp0",
      "name": "TP0 4h",
      "formatDetails": {
        "feature": "jexl:{name:get(feature,'start')}"  // <------
      },
      "adapter": {
        "type": "BedTabixAdapter",
        "bedGzLocation": {
// ...
```
2. Load JBrowse2 web and click on a feature in the respective track.

**Expected behavior**

The "Feature details" panel should show the evaluated result of the jexl expression. In the case of the example above it would the the start position of the feature. Instead, the Panel remains white and the Console (F12) shows an error traceback:
```
[mobx] uncaught error in 'Reaction[Autorun]' Error: TypeError: e.get is not a function
```

**Screenshots**

![image](https://user-images.githubusercontent.com/50179943/189363237-6ad771e8-79e0-4bed-8f87-22edbfb1340a.png)

**Version:**

JBrowse2 v2.1.2
Firefox 104.0
Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)
Ubuntu 20.04

**Additional context**

Using only variables in jexl (i.e. not a function call with feature as input) works, however:
```javascript
// ...
    {
      "type": "FeatureTrack",
      "trackId": "OrganismGenome_ChromatinStatesTp0",
      "name": "TP0 4h",
      "formatDetails": {
        "feature": "jexl:{name:feature.start}"  // <------
      },
      "adapter": {
        "type": "BedTabixAdapter",
        "bedGzLocation": {
// ...
```

Of course, this example above with the start of the feature does not make sense and I only use it to test it. Later on I have to integrate my own functions for more complex configuration callbacks, but these will need to access `feature` as well.

Also, I'm not a web developer and have little to no experience with Typescript/Javascript. I'm just a Bioinformatics PhD student that was tasked to implement a genome browser by his PI. So I hope that I'm not just missing something really obvious here.

**Comment by cmdcolin** [comment]
This is actually expected

The "feature details" panel receives a snapshot of the feature, so you get a plain js object instead of the "SimpleFeature" style object with the feature.get('...') function. Therefore, your solution using feature.start should be right and expected

The technical reason for all this: it is a plain js object because the feature detail panel need to be snapshottable (serialized into JSON so it can survive page refreshes, etc) which means it must be serialized into the session JSON snapshot. We could potentially "rehydrate" the feature back into a simplefeature object so it is a plain feature, but currently it is just a JS object so your Additional context solution is fine. Changing the behavior at this point could be a breaking change also, so it may stay the way that it is

**Comment by cmdcolin** [comment]
the docs should probably be updated to reflect this though! :)

**Comment by mriedl93** [comment]
So from what I understood, the consequence is that the configuration callbacks don't work at all anymore, right?

My example with `feature.start` is of course not what I want to achieve. Actually, I try to add a feature track of chromatin states computed with ChromHMM. Basically non-overlapping segments. Therefore, I wanted to show the track in a 'collapsed' display mode as well as with a color code reflecting the individual chromatin states. I would have done that with a configuration callback.

Now, I guess, the only solution is to have the color already in the BED file and using it e.g. like `jexl:{color:feature.field8}`, when column 8 has the state color in hex codes.

**Comment by cmdcolin** [comment]
most callbacks like color callbacks should still use e.g. `get(feature, 'field8')` or `get(feature,'start')`, but the "feature details" callbacks should instead can use feature.field8, feature.start, etc. like a plain json object

also, just for some more info to help try to explain "jbrowse's perspective" for why we even use the "get" function: some features (BAM and CRAM features especially) are expensive to serialize to JSON completely, and so instead, we call a "get" method so that it only serializes the necessary data.  this makes rendering all the features faster (this graph in the jbrowse release actually shows the speedup that removing serialization has https://jbrowse.org/jb2/blog/2022/04/26/v1.7.5-release/  the blue line is the time it took to render data before we removed serialization, and the red line is after we removed serialization from web worker. the green line is the embedded which didnt have serialization anyways). so then why is the feature formatter using plain json objects instead of the get method? well: serializing a single feature to JSON isn't that expensive, so the feature detail panel receives a JSON object of the feature, which helps it so that it can be serialized and deserialized (you can refresh the browser and the feature detail panel stays in place). 



PS having chromHMM style track is a great idea. we could consider having a way to make this easier! i remember we did make an example of it in jbrowse 1 https://jbrowse.org/code/JBrowse-1.16.11/?loc=ctgA%3A9894..31863&tracks=DNA%2CChromHMM&data=sample_data%2Fjson%2Fvolvox&tracklist=1&highlight=&nav=1&overview=1

**Comment by cmdcolin** [comment]
can check https://github.com/GMOD/jbrowse-components/blob/a7e7da90d75ad40104ebdf8933ae2e753f879a32/test_data/volvox/config.json#L989-L991 for format details example and https://github.com/GMOD/jbrowse-components/blob/a7e7da90d75ad40104ebdf8933ae2e753f879a32/test_data/volvox/config.json#L1430-L1467 for a color callback

**Comment by mriedl93** [comment]
Ah, now I get it! Sorry for my confusion.

I now managed to implement the configuration callback for coloring the chromatin states with a custom plugin. Much like the example in JBrowse1.

Thanks a lot for the help and explanations. From my side it is now solved and I would close the issue.

Thanks again and have a nice day!
