### ISSUE TITLE
adding bam tracks inplace doesnt seem to work

### ISSUE THREAD

**Issue by tensulin** [GMOD/jbrowse-components#3264]
Runninng jbrowse as a self hosted server.
I loaded a bam track inPlace, however the server still looks in the wrong directory 

Add a bam file, which is not in the Apache jbrowse root directory inPlace and see whether the track can load

**Expected behavior**

Error: HTTP 404 (Not Found) when fetching http://...

**Version:**
@jbrowse/cli/2.1.5 linux-x64 node-v12.22.12

Server: Debian11 5.10.0-18-amd64

Browser: Firefox
-->

**Additional context**

**Comment by cmdcolin** [comment]
Generally, you will want to use the other load options (copy,symlink,move) to put the file into your Apache directory. JBrowse is not able to access files that are not in your web server directory. The reason this is the case is JBrowse doesn't run on the server, so it actually can't read any files outside of the web server directory, JBrowse requests all the data from the client side which means the web server has to return the data, hence, the data has to be in the Apache directory :)

That is sort of why `--load inPlace` is meant for sort of advanced users, because it doesn't try to copy/move/symlink at all, and just puts exactly what you specified directly into the config, but in general, using the other --load options will be better

**Comment by tensulin** [comment]
Thanks for the information! I didnt realize that, I thought it would maybe add the path to the config. I will use symlink instead
