### ISSUE TITLE
Browser compatible API?

### ISSUE THREAD

**Issue by csmartj** [GMOD/jbrowse-components#3591]
Hello, I launched a jbrowse, using test data volvox, access the url API:
http://myurl?config=test_data/volvox/config.json&session=spec-{"views":[{"type":"SpreadsheetView", "uri":"test_data/volvox/volvox.filtered.vcf.gz","assembly":"volvox"}]}
In Firefox, it works fine, but in Google Chrome and edge, it shows an error:
**Error: HTTP 206 fetching test_data/volvox/volvox.filtered.vcf.gz**
Is it a bug?

**Comment by cmdcolin** [comment]
It's a little hard to tell. From what I can tell, our "live link" from https://jbrowse.org/jb2/docs/urlparams/#spreadsheet-view works in both firefox and chrome (the live link here https://jbrowse.org/code/jb2/main/?config=test_data/volvox/config.json&session=spec-%7B%22views%22:%5B%7B%22type%22:%22SvInspectorView%22,%20%22uri%22:%22test_data/volvox/volvox.dup.vcf.gz%22,%22assembly%22:%22volvox%22%7D%5D%7D)

what you report seems to indicate that some combination of server+browser behavior is misbehaving

some places we have seen this before is if the server enables Content-Encoding: gzip on the response. jbrowse does not generally want this to happen, and this is sometimes due to mime_magic from apache https://jbrowse.org/jb2/docs/faq/#bam-files-do-not-work-on-my-server


one way to fix is to rename your vcf files to not use the .gz extension, as that may trigger the behavior...might be able to use the canonical 'bgz' or something like that. alternatively, can try to look into your server config to not send Content-Encoding:gzip

**Comment by cmdcolin** [comment]
also make sure to report what version of jbrowse  you are using,since that is sometimes relevant

**Comment by cmdcolin** [comment]
(i know the faq link refers to BAM files but has affected many other file types including tabix vcf https://github.com/GMOD/jbrowse/issues/667 and bgzip fasta https://github.com/GMOD/jbrowse/issues/1291)

**Comment by csmartj** [comment]
1、my jbrowse version is @jbrowse/cli/2.4.1 linux-x64 node-v16.10.0，Does this have anything to do with the version? what version is this?
(the live link here https://jbrowse.org/code/jb2/main/?config=test_data/volvox/config.json&session=spec-%7B%22views%22:%5B%7B%22type%22:%22SvInspectorView%22,%20%22uri%22:%22test_data/volvox/volvox.dup.vcf.gz%22,%22assembly%22:%22volvox%22%7D%5D%7D) 
2、i rename zhe vcf files to : volvox.filtered.vcf , But it still reports an error in chrome：
**Error: HTTP 206 fetching test_data/volvox/volvox.filtered.vcf**
it works fine In Firefox
Content-Type: text/x-vcard; charset=utf-8

**Comment by cmdcolin** [comment]
That link is continuously deployed from the "main branch" of this repo.so.is basically the latest version. so basically v2.4.1. note that the cli version can be separate from the version you are using, check the "about" wider in the app or the version.txt file in the filesystem to see what is being used. It may match the cli but does not need to as they can be updated separately 

That 206 error is weird and my assessment of it being content encoding could be off base. What server are you using ? Do you have a live link?

**Comment by cmdcolin** [comment]
(note that content-type and content-encoding are separate and have very different consequences, if you can determine content-encoding being returned it may help)

**Comment by csmartj** [comment]
I did this test in chrome: 
the first time open the api: http://myurl?config=test_data/volvox/config.json&session=spec-{"views":[{"type":"SpreadsheetView", "uri":"test_data/volvox/volvox.filtered.vcf.gz","assembly":"volvox"}]}; It shows that the **Error: HTTP 206 fetching test_data/volvox/volvox.filtered.vcf.gz**
But on the page, i did this:
 A**DD->Spreadsheet view, Manually add URL: test_data/volvox/volvox.filtered.vcf.gz**, 
it's normal;
Now i open the api again: http://myurl?config=test_data/volvox/config.json&session=spec-{"views":[{"type":"SpreadsheetView", "uri":"test_data/volvox/volvox.filtered.vcf.gz","assembly":"volvox"}]},It can be accessed normally
so, this method can solve my problem, but the large amount of data will be troublesome

**Comment by cmdcolin** [comment]
it's hard to say what the issue is, but it's likely not necessarily an issue with jbrowse itself, it is probably something to do with your server. it's possible jbrowse could make a workaround for odd server behaviors, but it's worth looking at what your servers behavior is here

**Comment by cmdcolin** [comment]
any update? @csmartj if you can provide any server side details on your setup, might be able to help
