### ISSUE TITLE
Errors loading gff for text searching

### ISSUE THREAD

**Issue by alexjacobsCDS** [GMOD/jbrowse-components#3645]
We are seeing errors trying to load gff track.  This file has been sorted, bgzipped, and is being loaded with the Gff3TabixAdapter.
 
 See the error below

![image](https://user-images.githubusercontent.com/48565768/232133451-3fceb626-62f0-4012-9324-9b85acf8f995.png)
 
This seems to be complaining about there being multiple features with the same id. 
![image](https://user-images.githubusercontent.com/48565768/232151411-41d958b2-d269-49e8-ac08-251aab8c45d6.png)
bu they are different annotations and not "multiline", the coordinates differ as well.

 This is happening to a whole lot of our genomes. another example 
 
![image](https://user-images.githubusercontent.com/48565768/232151659-43d97b92-e3d9-4d74-ab20-220d4810f290.png)

 
 any help on how to fix this would be welcome

**Comment by garrettjstevens** [comment]
In a GFF3, because a feature can have multiple locations, lines with the same ID must represent a single feature. This is what is meant by a "multiline" feature. Here's the description from the [GFF3 spec](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md):

<blockquote>
<dl>
  <dt>ID</dt>
  <dd>Indicates the ID of the feature.   The ID attribute is required for  features that have children (e.g. gene and mRNAs), or for those that span multiple lines, but are optional for other features.  IDs for each feature must be unique within the scope of the GFF file. In the case of discontinuous features (i.e. a single feature that exists over multiple genomic locations) the same ID may appear on multiple lines. All lines that share an ID must collectively represent a single feature.</dd>
</dl>
</blockquote>

To load this GFF3 properly, you'd need each individual feature to have a unique ID. Are these GFF3s you created, or did you download them from somewhere? You may need to address this with whatever upstream source you obtained the GFF3 from.

**Comment by alexjacobsCDS** [comment]
@garrettjstevens thanks for the quick reply.  These are from [NCBI](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/331/145/GCF_000331145.1_ASM33114v1/) but they may be outdated.  In the most recent versions see these lines have an updated ID field

i.e.
![image](https://user-images.githubusercontent.com/48565768/232156035-2ad28841-38d9-45dc-8061-1f04cdf5cfc2.png)
 
 I appreciate your help! Closing this issue
