### ISSUE TITLE
Synteny views: Error: Data exceeds maximum string length (512Mb)

### ISSUE THREAD

**Issue by MikeAxtell** [GMOD/jbrowse-components#3664]
**Describe the bug**

Using a whole-genome self to self alignment (.paf format) produced by minimap2 to explore synteny, the dotplot synteny viewer and the linear synteny viewers will not load. It states "Error: Data exceeds maximum string length (512Mb)".

**To Reproduce**

1. Produce a large .paf file by self-to-self minimap2 alignment of a genome assembly from a recent polyploid. ~ 505Mb genome assembly.
2. Add a dotplot view or a linear synteny view in jBrowse2, self-to-self (same genome assembly).
3. Specify the relevant .paf file and launch.

**Expected behavior**

Expected to see dotplots and linear synteny views.

**Screenshots**

![Screenshot 2023-04-25 at 11 51 47 AM](https://user-images.githubusercontent.com/6854537/234333431-d3f1d580-6465-44d8-ac48-857dbe054ad0.png)

**Version:**

JBrowse2 Desktop 2.4.1 on Mac (M1 Pro chip, running Ventura 13.3.1)

**Additional context**

Seems obvious that the .paf is too big (the .paf file size is 690Mb). Any tips to reduce .paf size, or other work-arounds?

**Comment by cmdcolin** [comment]
good question. The 512Mb limit is something we may be able to fix by parsing the file line by line instead of loading it entirely as a string. we may also investigate loading compressed versions of the data for in memory compactness. 

if you want to try things "today", you can maybe not use -c (CIGAR) to reduce size, or manually filter out small alignments to reduce size now

we are working on scalability of the synteny functionality to handle larger files, and that's a multi-prong effort, so can keep you updated on that too
