### ISSUE TITLE
SVG textLength being automatically calculated leads to inconsistent look

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#381]
![localhost_3000_ (5)](https://user-images.githubusercontent.com/6511937/60676846-eac59b00-9e4d-11e9-9791-50f3648db9b1.png)

Avoiding this could involve proper usage of calculating textLength or not using textLength as an actual SVG attribute

**Comment by cmdcolin** [comment]
It seems like removing textLength completely helps. Not sure if there is a reason it was there before

**Comment by garrettjstevens** [comment]
Dang, I hoped this workaround would look better for most data. I checked with some, but didn't check exhaustively. I'll try to explain what's going on here.

The problem is determining how much space to leave for the feature rectangle. The width of the glyph is easy, but you also have to allocate for the width of the label (and/or description).

As far as I can tell, there is no good way to calculate the width of SVG text without rendering it (unless you forced it to use a specific mono-spaced font, in which case you could measure the character width beforehand and code that in, but I don't think that would look nice). The only way I could find to measure it was to first render the text in an invisible element, measure it, and then render it again ([ref](https://maximilianschmitt.me/posts/how-to-determine-the-width-and-height-of-svg-text-before-rendering-with-raphael/)). That sounds too heavyweight, though, especially if there are a lot of labels on the screen.

Before, the code assumed each character's width was 75% of its height, which is basically always an over-estimate to make sure there is enough space. It led to less efficient feature packing, though, since most rectangles with long text/labels were a lot wider than they needed to be.

I tried to get around this by using textWidth to specify exactly what the width was. It also forces all labels/descriptions to fit within the maxFeatureGlyphExpansion. I found that setting a textWidth of 0.55 * numberOfCharacters led to natural-looking text in the examples I looked at (obviously not all text, though).

I can see two potential solutions. One is just going back to over-estimating the width to make sure there is room. That makes it difficult to force the label/description to fit within the maxFeatureGlyphExpansion, though. The other option is use some heuristic to decide if the label/description is likely longer than the glyph and then only use textWidth in that case. That would result in more text just using their natural spacing.

Also, come to think of it, maxFeatureRectExpansion is probably a more accurate name than maxFeatureGlyphExpansion, since the glyph isn't being expanded, it's the rectangle around it that is.

**Comment by cmdcolin** [comment]
Possible estimator https://bl.ocks.org/tophtucker/62f93a4658387bb61e4510c37e2e97cf

**Comment by cmdcolin** [comment]
Kinda hacky for sure..

**Comment by cmdcolin** [comment]
While the idea of precisely calculating the proper text width for the layout is not done via getBBox or similar, I think using the "upper limit estimate" of fontWidth*0.55 may hold up for awhile and we can see if it needs more adjustments sometime. One other thing is that the elipses are technically added after the max width of the text in #418 which might be a bit weird, but hopefully this holds up too
