### ISSUE TITLE
Vcf Feature appears to be repeat-rendered once per content block

### ISSUE THREAD

**Issue by bbimber** [GMOD/jbrowse-components#3835]
This is a live URL that should illustrate what I'm reporting. I'm not sure if this is a bug or intentional. See here:

https://prime-seq.ohsu.edu/home/jbrowse-jbrowse.view?session=mgapF&location=1:8417..8544

you'll see that is displaying a VCF with one variant. If you inspect the page and look for the string "SNV A -> T", you'll find there are three nearly identical <text> elements all layered on top of each other. If I'm interpreting this correctly, the track renders with three different content blocks. Each block must be loading data independently. If you look at the x coordinates, you'll see each content-block div is rendering it's own variant, and shifting the x coordinates outside of its region to put that variant in the correct spot. It seems like maybe each chunk of the track is grabbing data independently and trying to render all features within the whole window, rather than it's specific chunk?

Our code does have some custom elements, but I dont immediately see anywhere we are changing that codepath. Should this be happening?

Note: this is @jbrowse/core 2.6.2

**Comment by bbimber** [comment]
It appears to repro on your demo site here: https://jbrowse.org/code/jb2/v2.6.2/?config=test_data%2Fconfig_demo.json&session=local-UbtW1tGT4

You'll see there are duplicate <g> and <text> blocks with the string nssv15767046. Maybe I dont understand something on SVG, but they seem to be right on top of each other.

![image](https://github.com/GMOD/jbrowse-components/assets/7724863/5eb04aeb-807b-4dc5-8620-86724e167c08)

**Comment by cmdcolin** [comment]
this is expected due our "block based" rendering system.

basically jbrowse renders multiple blocks corresponding to different genomic regions side by side. each one is basically an independent `<div>`, and inside the `<div>` is the result of the renderer, which may be an `<svg>` node for example ("svg node" and "svg canvas"). the contents from one block cannot bleed out into another block because each block has separate `<svg>` canvas. therefore it is duplicate rendered in each svg canvas.


the question i suppoise is: are you seeing problems with the way this occurs?

**Comment by cmdcolin** [comment]
one other question one might ask is: why would the feature which is really so small like a SNP be duplicate rendered? this is to accommodate whether the feature labels can affect the layout from each block. unfortunately blocks are not so independent, they need to interlock so they sometimes duplicate some work

**Comment by bbimber** [comment]
> this is expected due our "block based" rendering system.
> 
> basically jbrowse renders multiple blocks corresponding to different genomic regions side by side. each one is basically an independent `<div>`, and inside the `<div>` is the result of the renderer, which may be an `<svg>` node for example ("svg node" and "svg canvas"). the contents from one block cannot bleed out into another block because each block has separate `<svg>` canvas. therefore it is duplicate rendered in each svg canvas.
> 
> the question i suppoise is: are you seeing problems with the way this occurs?

Thanks for the reply. No, I'm not really seeing problems. When I updated JB versions, one of our automated tests broke (which was counting variants), so I was surprised to see this. In my case these are Selenium tests that count variants using Xpaths. The problem is that different agents are behaving differently. I havent figured out whether they are actually rendering a different number of elements, or whether they are behaving differently as far as what's considering visible or not.

I understand the side-by-side-rendering blocks, and I figured something like this was the root of why this is happening. I see your point about features and/or labels sometimes bleeding across strict borders. It's also a bit surprising to see what seems like everything is duplicated across every block. Is there any limitation on what's duplicated vs. not? In my first link there is just one single feature in the entire view, yet it's getting re-rendered 3x. 

Anyway, like you say, this doesnt appear to harm the display. It would stand to reason that adding redundant elements to the display could hurt perf for very feature-dense displays, but I dont have a concrete example of that. If you are aware of this and dont think it's a problem you can close the issue. I'll figure out a way to work around these test issues.

**Comment by cmdcolin** [comment]
just as you mention, the repeat renderings are an expected outcome, it is indeed a perf issue but we are aware of it. some sort of back burner optimizations have been conceived that could help with this but it might be a little ways out :)

can probably close for now

just as a trivia note: jbrowse 1 actually did not repeat render things for its htmlfeatures track, but since each individual block is it's own svg canvas in our svg display, it is repeat rendered currently..
