### ISSUE TITLE
support for bedMethyl tracks

### ISSUE THREAD

**Issue by nextgenusfs** [GMOD/jbrowse-components#3842]
ONT is now making methylation analysis a bit easier, in some cases it can come for "free" now with base calling.  Their new base caller `dorado` https://github.com/nanoporetech/dorado can now generate methylated BAM files directly. ONT then also provides `modkit` https://github.com/nanoporetech/modkit which can compute a `bedMethyl` formatted "bed" file from these data.  It would be nice to be able to display the bedMethyl tracks: defined here https://github.com/nanoporetech/modkit#bedmethyl-column-descriptions from `modkit`, but there it points to another format (bed9+2) here https://www.encodeproject.org/data-standards/wgbs/. 

> The bedMethyl file is a bed9+2 file containing the number of reads and the percent methylation.
> 
> Each column represents the following:
> 
> 1. Reference chromosome or scaffold
> 2. Start position in chromosome
> 3. End position in chromosome
> 4. Name of item
> 5. Score from 0-1000. Capped number of reads
> 6. Strandedness, plus (+), minus (-), or unknown (.)
> 7. Start of where display should be thick (start codon)
> 8. End of where display should be thick (stop codon)
> 9. Color value (RGB)
> 10. Coverage, or number of reads
> 11. Percentage of reads that show methylation at this position in the genome
> 

Mostly I think what would be of use to graph as a numerical value would be column 11 which is the percent of methylated bases at each position.

**Comment by nextgenusfs** [comment]
Note that one could just re-format with column 11 in place of the score (col 5) and then load as a quantitative BED file.
![image](https://github.com/GMOD/jbrowse-components/assets/6164308/6c59e35c-003e-41af-ac7d-656b1703f6a7)

**Comment by cmdcolin** [comment]
is it expected that the bedMethyl track is so much more sparse than the bam track above it? also that modkit issue is curious, why not all tabs!

**Comment by ArtRand** [comment]
The bedMethyl track there does look a little strange. Ideally the bar heights are the %-methylated, this looks more like it's the valid coverage (but I'm not sure). The bedMethyl output from `modkit` can also have %-methylated for multiple base modifications (e.g. %5hmC %5mC), if there was a way to get a stacked histogram that would be awesome. 

As far as the mixed spaces and tabs. As I mentioned on the other thread, this was one way I found the default output would be accepted by the browser I often use, and you could still use awk or anything that will split on whitespace. I agree it's a lousy hack, I'm more than happy to iterate towards a good way to directly parse the bedMethyl files.

**Comment by nextgenusfs** [comment]
> is it expected that the bedMethyl track is so much more sparse than the bam track above it?

Probably (?), this is a fungal genome that has apparently low levels of methylation. I didn't try hard to find a region with more methylation. @ArtRand said it was also possible to output in `bedgraph` so maybe I'll try that to see how it is displayed. Let me see if I can get some examples of what I'm seeing that are more relevant and then maybe we can figure out the best way to display the data.  But agree that %-methylated would be best thing to display.  It's actually what I tried to do here, ie took column 11 and put it in the normal bed format at column 5 (score).

**Comment by cmdcolin** [comment]
gotcha. I agrtee something like "%-methylated" is a good metric to plot. I have seem some plots that using like a sliding window to try to smooth out the levels too... example https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009524

just something to kind of take the noisyness out, and also allow viewing at large scales...would be great to make a demo kinda like that

**Comment by cmdcolin** [comment]
(i'm not familiar with running the analysis tools myself but if you are able to provide the commands or links to tutorials I could definitely give it a try also)

**Comment by Ge0rges** [comment]
@cmdcolin I may have misunderstood, but would you like example bedmethyl files matching a provided FASTA?

**Comment by cmdcolin** [comment]
yes that would be great. If there was the nanopore reads to go with it as well it might be helpful also because then I can check the correspondence, but just the bedmethyl file would be helpful

**Comment by cmdcolin** [comment]
can email me directly or paste link here

**Comment by Ge0rges** [comment]
Here's a [link](https://www.dropbox.com/sh/rzsfzjtjoe5ypap/AADwDvUrexmTLkXf96SU1a5Ra?dl=0) to an indexed genome (FASTA file), corresponding bedmethyl, and bedgraph. Let me know if I can be of any more help. The folder will be hosted for 10 days @cmdcolin.

**Comment by cmdcolin** [comment]
@Ge0rges just FYI I did download this. it would be nice to have the BAM files also if they are available as seeing the correspondance of the BED and the BAM may help visually for me (see comments above where I was a little confused about this correspondance...would be nice to see them both at once in my own browser)

**Comment by Ge0rges** [comment]
Hi @cmdcolin, I've uploaded the corresponding bam to that folder.

**Comment by cmdcolin** [comment]
hi there,
I just got around to working a bit on this. I released some updates in v2.17.0 that can display bedMethyl files. They can be displayed as a "multi-quantitative track" so it is a single track, and each row gets it's own modification type

i also refactored the modification code a bunch to take into account probabilities from the ML tag a lot more so it doesn't double count modifications when h and m are listed at the same position, just takes the highest likelihood one

![image](https://github.com/user-attachments/assets/589214e3-58cd-4460-a59a-e4e37c00268e)


Right now I made fraction_modified the default 'score' but I noticed that sometimes it can get tripped up where e.g. there is a single h in a position, then it can display 100% modified, but this can be a little odd because it is just a single read in a stack of 30+ reads. I could also plot the raw n_modified count from bedmethyl but its nice when it is normalized by read depth, so not sure what is best

Anyways, feel free to let me know if you have any thoughts or can try it out

I used modkit to run over a sample file from COLO829 and made this track config

```
{
      "type": "MultiQuantitativeTrack",
      "trackId": "COLO829_tumor.ht_modkit.bed_multi",
      "name": "COLO829_tumor.ht_modkit.bed (as MultiQuantitativeTrack)",
      "adapter": {
        "type": "BedTabixAdapter",
        "bedGzLocation": {
          "uri": "https://jbrowse.org/genomes/GRCh38/COLO829/COLO829_tumor.ht_modkit.bed.gz",
          "locationType": "UriLocation"
        },
        "index": {
          "location": {
            "uri": "https://jbrowse.org/genomes/GRCh38/COLO829/COLO829_tumor.ht_modkit.bed.gz.tbi",
            "locationType": "UriLocation"
          },
          "indexType": "TBI"
        }
      },
      "assemblyNames": ["hg38"],
      "category": ["Methylation"]
    }
```

you can get this interactively via point and click in the UI if you load a track, and then force it to be a Multi-quantitative track instead of a feature track at the add track screen.

**Comment by cmdcolin** [comment]
(over a year since last update but better late than never!) cc @nextgenusfs @ArtRand @Ge0rges 

random sidenote 1: i noticed also that the bedMethyl from modkit had tabs in it instead of spaces so that made me happy :)

random sidenote 2: it would be nice if there was a header or something for bedMethyl to indicate that it is...a bedMethyl file and not a normal bed file...but i know BED is notoriously underspecified. it can be hard to tell just given a random bed file how jbrowse should display the data

**Comment by cmdcolin** [comment]
might close for now, but the score issue mentioned above ("Right now I made fraction_modified the default 'score'"...) could be worth revisiting
