### ISSUE TITLE
CLI install deprecation warnings

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3869]
Currently running npm install -g @jbrowse/cli outputs

```
npm WARN deprecated @oclif/command@1.8.36: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/help@1.0.15: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/errors@1.3.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/parser@3.8.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/config@1.18.16: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @oclif/config@1.18.17: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.


```

would be nice to avoid users experiencing this. Could upgrade to oclif CLI 2 or change to another CLI lib

**Comment by cmdcolin** [comment]
for a possible 'conversion' or 'update' to yargs (popular node.js CLI tool) i created a sample template here for how it might be done, with add-track and add-assembly sketched out https://github.com/GMOD/jbrowse-components/tree/yargs

**Comment by cmdcolin** [comment]
would be curious what you think @garrettjstevens about possible yargs conversion. I have tried to upgrade oclif a couple times but it never quite worked...dont have notes though

**Comment by garrettjstevens** [comment]
I'd like to keep oclif if it's not too much trouble, since I don't want us to introduce bugs in converting the code. I was able to get the `create` command updated in a branch here: https://github.com/GMOD/jbrowse-components/compare/oclif_2_upgrade_gs

When I tried to get the test for that file working, though, I couldn't ever get it to run. If we can't get the oclif tests working and yargs has a good, easy way to test, though, then maybe it's worth the conversion.
