### ISSUE TITLE
AlignmentTrack not working when using CRAM which bzip2 compression 

### ISSUE THREAD

**Issue by Imoteph** [GMOD/jbrowse-components#4002]
When a Cram file is compressed with bzip2 activation, jbrowse2 is not able to show the track. It shows `bzip2 is not defined` error message.

If a cram file is used with has only been compressed with the standard `-C` flag, jbrowse2 is able to show this track as expected:
`samtools view -C -T etc...  `
But using this notation which activates bzip2, jbrowse fails to show the track
`samtools view   -T reference  -O 'cram,use_bzip2'`

**Expected behavior**

view of the cram file, regardless if bzip2 is activated or not

**Screenshots**
![image](https://github.com/GMOD/jbrowse-components/assets/11348064/dc7f48f9-f9fd-407c-a931-d0077e7179fe)
### With JbrowseR
![image](https://github.com/GMOD/jbrowse-components/assets/11348064/f9eb108d-c811-4113-8d71-c02bfa3c1741)
### With Jbrowse2 
![image](https://github.com/GMOD/jbrowse-components/assets/11348064/604f2018-797c-4e17-bdfa-137e967f0200)

**Version:**
2.7.1

**Comment by cmdcolin** [comment]
interesting. cram-js does make a basic attempt to support bzip2 since v1.6.0 of cram-js which has been included https://github.com/GMOD/cram-js/blob/master/CHANGELOG.md#v160


I tried creating a bzip2 file locally, and it worked for me

```
samtools view   -T volvox.fa  -O 'cram,use_bzip2' volvox-sorted.bam -o volvox-sorted-bzip2.cram
samtools index volvox-sorted-bzip2.cram
jbrowse add-track volvox-sorted-bzip2.cram ...
```

loaded in browser

I wonder if there is something related to JBrowseR causing the issue? the CRAN version of JBrowseR has not been updated for a long time (need to redeploy it to CRAN!), but if you are using the devtools::install_github it should be getting a more recent version

**Comment by cmdcolin** [comment]
screenshot of my bzip2 track working

![Screenshot from 2023-10-20 11-26-42](https://github.com/GMOD/jbrowse-components/assets/6511937/8dc80f19-6449-46b5-a602-c399e51228be)

**Comment by cmdcolin** [comment]
I actually see that there could be a real issue with this in cram-js, and that maybe the small test track wasn't enough to exercise the test case enough

**Comment by cmdcolin** [comment]
I am not sure I am able to generate a bzip2 file locally even using those samtools flags (maybe it dynamically decides to use bzip2 only when appropriate for the data) but I found cram-js was not properly importing the bzip2 module due to thinking it was a global. I republished cram-js with a hopeful fix and if you have a setup to get the latest version of dependencies e.g. with "yarn upgrade" then you should be able to get this latest version with cram-js updated

**Comment by cmdcolin** [comment]
should be fixed on main branch...thanks for reporting!

**Comment by cmdcolin** [comment]
xref #4007

**Comment by Imoteph** [comment]
@cmdcolin could you maybe so kind as to give me hint how I could update in JBrowseR the issue, I tried but it did not work (doing an upgrade and building a new package)? I know this thread is related to browse but I didn´t want to open a new ticket as this is tightly connected. But if you want, I can open a new ticket at the respective repo.

**Comment by cmdcolin** [comment]
@Imoteph I pushed an update to the JBrowseR repo with an updated build. just ran these two commands in the JBrowseR repo

```
yarn upgrade
yarn build
git add .
git commit -m "Update build"
git push
```

this updates all yarn.lock dependencies according to semver which gets bugfixes like the new @gmod/cram version, and then runs a new webpack build (the webpack build is currently stored in the JBrowseR repo) and then I pushed that


you should be able to do a new devtools::install_github of the repo now
