### ISSUE TITLE
Add Chm13 as Assembly track with all the reference.

### ISSUE THREAD

**Issue by adaware-loxo** [GMOD/jbrowse-components#4117]
**Is your feature request related to a problem? Please describe.**
I want to add chm13 as reference assembly to the existing hg19 and hg38

**Describe the solution you'd like**
I tried adding using the  "jbrowse add-assembly", but this only adds the assembly, I want to add all the reference as well (chr1-22).

**Describe alternatives you've considered**

If you could add it to config.json that would be highly appreciated

**Comment by cmdcolin** [comment]
hi there
are you using jbrowse-desktop or jbrowse-web? we have an example of using the chm13 genome in our "config_demo.json" here https://jbrowse.org/code/jb2/v2.9.0/?config=test_data%2Fconfig_demo.json&session=share-yEBcwhNVZk&password=s9ZiM

I know also that UCSC has tagged the CHM13 as "hs1" so that might be a good source of data. I believe the version I linked above were manually downloaded from https://github.com/marbl/CHM13

I am not exactly sure what you mean where you say "it only adds the assembly, I want to add all the reference as well (chr1-22). The "jbrowse add-assembly" command basically is used to  load a FASTA file with all the chromosomes. There are also gene annotations e.g. in GFF format and such, and those can be added via "jbrowse add-track"

**Comment by adaware-loxo** [comment]
Hi, 
I'm using Jbrowse-web.
Thank you for pointing to the config_demo.json, that helps a lot.
