### ISSUE TITLE
Add ability to make GC content track a separate track in the tracklist

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4278]
Currently it can be enabled as a 'display' on the referencesequencetrack, but would improve discoverability as a separate entry

example of manually enabling a gccontentadapter with a quantitativetrack is a possible workaround, but doesn't have editability

```
    {
      "type": "QuantitativeTrack",
      "trackId": "mytrack",
      "name": "GC content",
      "assemblyNames": ["volvox"],
      "adapter": {
        "type": "GCContentAdapter",
        "sequenceAdapter": {
          "type": "TwoBitAdapter",
          "twoBitLocation": {
            "uri": "volvox.2bit",
            "locationType": "UriLocation"
          }
        }
      }
    },
```

**Comment by cmdcolin** [comment]
requested via office hours

**Comment by abjanssen** [comment]
Hi Colin, 
it was great talking to you yesterday, where we discussed this issue as well.
During our call, I mentioned the error that the NucContent plugin gives when trying to change the settings for the GC content calculations. After some tinkering, I've gotten the code to work, so that the user may now change these settings themselves.

I've submitted an issue to the GitHub page of the plugin, but I thought you might be interested as well, considering our discussion yesterday.

You may find the issue here:
https://github.com/jjrozewicki/jbrowse2-plugin-nuccontent/issues/2

**Comment by cmdcolin** [comment]
I can see the error #2 ran into, and that error can be fixed in jbrowse core also... I made a fix on this branch to allow plugins to continue using material-ui/core/styles as the makeStyles import

https://github.com/GMOD/jbrowse-components/pull/4288

I also made it on that PR where you can now create a "GCContentTrack" track type from within jbrowse 2 separate from the ReferenceSequenceTrack

example track config

```
{
      "type": "GCContentTrack",
      "trackId": "volvox_gc",
      "assemblyNames": ["volvox"],
      "name": "GCContent",
      "adapter": {
        "type": "TwoBitAdapter",
        "twoBitLocation": {
          "uri": "volvox.2bit",
          "locationType": "UriLocation"
        }
      }
    },
```

hope that helps

you can try out this branch with

```
jbrowse create --branch gccontenttrack # or jbrowse upgrade --branch gccontenttrack

```

**Comment by cmdcolin** [comment]
might close for now. this is now possible, and could be documented. xref #3584
