### ISSUE TITLE
Default initial zoom level for synteny view should be far enough out to show some features

### ISSUE THREAD

**Issue by ihh** [GMOD/jbrowse-components#4372]

**Comment by garrettjstevens** [comment]
This issue comes from something we noticed when trying out synteny views with some Apollo users today. When you open a linear synteny view, the linear views are zoomed in by default, at least for the grape vs peach demo:
![image](https://github.com/GMOD/jbrowse-components/assets/25592344/ad92f724-1a52-43da-8d37-27cf97b4cf12)

This can lead to situations where it's hard to tell if the synteny data has loaded or not, since the synteny track is blank and doesn't have e.g. a track label. If the linear views were zoomed out by default (like when you open a single linear genome view), it would make it more likely to see data on the screen, but also might load a lot of data if using a large indexed synteny file. This is where #4371 might be useful.
