### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by MeiDongI** [GMOD/jbrowse-components#4512]
I got this error from JBrowse, here is the stack trace:

```
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
SessionLoader.ts:200:27 (at Object.fetchConfig ()
SessionLoader.ts:330:7 (at async Object.afterCreate ()
```

**Comment by cmdcolin** [comment]
this error would indicate that an HTML file is being returned when the config.json is trying to be fetched. you could probably reproduce this in your web browser by visiting the link e.g. "http://yourhost/jbrowse/config.json" to confirm this

this could be because your server is returning a 404 as an HTML file (and not the proper status code), or this is a dev server that is doing this, or it is a permission denied error like a 403. if you can narrow down what it is, then we might be able to provide further help but it's likely a server side issue like this

**Comment by cmdcolin** [comment]
let me know if you have any continued issues....might close for now

**Comment by ShuaiBinyu** [comment]
# I also met this question.
# This is a way to deal with it.
# ubuntu 22.04
- install
```
sudo apt install xsel
sudo apt install xvfb
```
- start
```
xvfb-run npx serve .
```
# This error is usually caused by a failed attempt to copy the server address to the clipboard. This may be due to the fact that you do not have xsel tools installed on your system or are running in a headless environment.``` xvfb-run npx serve . ```.This will run your commands in a virtual display environment, avoiding clipboard-related issues.
# I hope this helps.
