### ISSUE TITLE
Support PIF format on gui

### ISSUE THREAD

**Issue by alpapan** [GMOD/jbrowse-components#4565]
could we please allow the user interface to load a PIF via the [PairwiseIndexedPAFAdapter](https://github.com/GMOD/jbrowse-components/issues/3974)?

at the moment when i want to look at synteny, I have to select a PAF and then manually edit the track's config.

**Comment by cmdcolin** [comment]
thanks for making this request, definitely should be added!

**Comment by cmdcolin** [comment]
made a basic implementation of this in the now released v2.15.3 :)

**Comment by alpapan** [comment]
yeah thank you works! question: is it better to create a csi or tbi index?

**Comment by cmdcolin** [comment]
the major difference is that CSI supports indexing larger genomes e.g. where individual chromosomes are larger than 2^29 (~512Mbp) such as wheat (TBI is fundamentally unable to index chromosomes larger than that, BAI for that matter too, which is why BAM sometimes also has CSI index)


there are smaller differences but generally you can use TBI unless you are working on an organism with super long chromosomes
