### ISSUE TITLE
Error "Cannot read properties of undefined (reading 'muiName')" when using `@jbrowse/react-linear-genome-view`

### ISSUE THREAD

**Issue by yeweiyang96** [GMOD/jbrowse-components#4609]
**Describe the bug**

When I use the package @jbrowse/react-linear-genome-view, I encounter the following error:
`
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'muiName')
    at createSvgIcon (/Users/mac-studio/Desktop/workshop/g4vista-web/g4vista/node_modules/@mui/material/utils/createSvgIcon.js:24:31)
    at <anonymous> (/Users/mac-studio/Desktop/workshop/g4vista-web/g4vista/node_modules/@mui/icons-material/esm/Menu.js:5:16)
`

This issue does not occur when using version 2.12.0. I also cloned the **_jbrowse-react-linear-genome-view-vite-demo_** repository, and the same issue appears there as well.

**Version:**2.15.4
MacOS 15.0.1(M1) Chrome

**Comment by cmdcolin** [comment]
thanks for reporting this. from what I can tell, production builds actually work but this issue does come up in dev mode. i'll see if i can track it down...

**Comment by cmdcolin** [comment]
I believe is the culprit to this bug https://github.com/mui/material-ui/pull/43624 (@mui/icons-material) which happened in @mui/icons-material 6.1.0



I pushed a change to our jbrowse-react-linear-genome-view-vite-demo to force use of @mui/icons-material v6.0.2 instead of the newer 6.1.0 which fixes it for now, but in the future, we'll probably want to track this down and fix it better so we don't rely on this
