### ISSUE TITLE
Make desktop heavyweight browser product

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#484]
Using electron, we can make a desktop version of app that can target people using private human data on their personal machines more easily

**Comment by cmdcolin** [comment]
Alternative: progressive web app api's suggest that keeping filehandles across browser reloads may be possible in the future, but it's not there and also doesn't really convey the privacy of a desktop app in the same way as a real downloaded app

**Comment by rbuels** [comment]
Steps for this:

* make `packages/jbrowse-sv-inspector-desktop`
* make a new product and build system that builds an electron app with React
** probably start with an electron+react boilerplate skeleton?
* pull some stuff in from jbrowse-web or the protein widget to get a product running

**Comment by garrettjstevens** [comment]
Bit of an update here: getting an electron app itself to run in a monorepo seems fine, but getting the build tools (which we need to package/distribute the app) I've tried is not simple. I've been using `electron-forge` (which uses `electron-packager` internally), and it makes assumptions about locations of `node_modules` and `devDependencies` that don't always apply in yarn workspaces.

For now I'm going to skip over the build system stuff and just try to get an app working, since that's what we really need, and maybe split out build system stuff into a different task.

**Comment by rbuels** [comment]
It would be kosher to add a little bit of shell scripting to make it
happy.  Perhaps create a temporary “build” directory, copy or symlink or
re-yarn everything into it, and run the build in there. It’s a common
pattern.

**Comment by rbuels** [comment]
Not saying it’s what you have to do, just that it’s a fine option.
