### ISSUE TITLE
jbrowse-cli initial skeleton

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#55]
We intend to make a CLI for doing some data loading steps and probably name indexing

**Comment by cmdcolin** [comment]
JBrowse 2 multi-tool CLI will be made with something similar, having subcommands

```
# the prepare-refseqs workflow can be adding an indexed FASTA
jbrowse add-assembly --indexedFasta file.fa --config test_data/hg19/config.json
# adding tracks, e.g. a BAM file involves similar steps, just specifying the BAM file path (likely move or copy the BAM file)
jbrowse add-track --bam file.bam --bai file.ba.bai --config test_data/hg19/config.json
# adding GFF requires using tabix first, adding a plain gff might be a special add on to the CLI later
jbrowse add-track --tabixGff file.gff.gz  --config test_data/hg19/config.json
```

We will basically be appending json snippets into "tracks": [], no need to do mst validations from command line

Additional considerations

```
# for plugins with some custom json hunk
jbrowse add-track --custom '{ custom json here }'
# example for setting a default session
jbrowse set-default-session --view LinearGenomeView --tracks 'track1,track2,track3'

```

**Comment by garrettjstevens** [comment]
[yargs](https://yargs.js.org/) seems to be the most popular node CLI parsing library, but [oclif](https://oclif.io/) is recommended by [TypeScript](https://www.typescriptlang.org/docs/home.html). I think I'm going to try oclif first since it's got the best TypeScript support (and includes all the stuff to make TypeScript runnable in node) and also enables us to easily create a standalone tool if we want.

**Comment by rbuels** [comment]
initial skeleton done, made follow-on issues #1013 #1014 #1015 #1016 #1018

**Comment by garrettjstevens** [comment]
Skeleton done in #1003
