### ISSUE TITLE
JBrowse web crashes after refresh when a track that is deleted from config.json is loaded in the instance

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#560]

**Comment by garrettjstevens** [comment]
This is because currently by default saving to local storage is turned off. Adding a track adds it to the config, and the only way we currently have of saving the config is in local storage. Since the config isn't saved, on refresh the session tries to reference a track config id that doesn't exist.

I think we turned off local storage so that during development we could use the URL exclusively to control the session. Is that something we still want?

One thing we could do is separate the session and config local storage options so they can be enabled separately.

**Comment by rbuels** [comment]
Well, can't use the URL in dev these days if you have a spreadsheet in the session, that's for sure.

**Comment by rbuels** [comment]
this depends on #741

**Comment by rbuels** [comment]
i think this is fixed with a combination of the admin server, session tracks, and #1353

**Comment by cmdcolin** [comment]
#1353 had to get reverted due to #1371 issues, so maybe just reopening here

can review #1371 for the issues with #1353

**Comment by cmdcolin** [comment]
the tests would pass but the error messages in the travis-ci also reflected runtime behavior where the dotplot wouldn't initialize properly

**Comment by rbuels** [comment]
Well let's see if we can get this squared away, either by making #1353 work with dotplot, or some other solution.
