### ISSUE TITLE
make a hierarchical track selector

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#6]
Takes a structure of just track names and ids, and the categories they go under, and make a react implementation of the hierarchical track selector, pretty much exactly like JBrowse 1.

**Comment by garrettjstevens** [comment]
I've got an initial layout going in the add_track_selector branch. Here's what it looks like:
![image](https://user-images.githubusercontent.com/25592344/46911423-1c49af80-cf29-11e8-9ab1-0fc5b0cec217.png)

The little "+" button in the bottom right is an idea I had. It might make sense to have users use that button to add new tracks instead of (or in addition to?) the top menu?

I still need to implement the track filter box.

**Comment by garrettjstevens** [comment]
This is now mostly done and merged into master, including being hooked up to MST. The track selector's only state is whether each section is collapsed or open. For everything else it uses the state of the tracks. Just need the track filter box and them some tests.

**Comment by rbuels** [comment]
sounds like this is done, closing
