### ISSUE TITLE
svg export

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#61]
a linear genome view should be able to export its currently visible stuff to an svg file

this will include putting any visible canvas tracks into svg images in the export

**Comment by cmdcolin** [comment]
I made a random attempt at svg export here cause I figured why the heck not

https://github.com/GMOD/jbrowse-components/tree/export_svg

Unfortunately, canvas2svg does not work in a webworker so I came to the conclusion that I needed a full alternate svg renderer for PileupRenderer, or we just create our own little canvas2svg layer

But this is what it looks like exporting a block to svg

![image (10)](https://user-images.githubusercontent.com/6511937/72755007-a948d300-3b86-11ea-99aa-c482024e4e62.png)

We would also probably have to stitch together SVG chunks, lots of other stuff, but I thought this was a fun first step

**Comment by cmdcolin** [comment]
Current branch can export a ruler, a pileup track and gene track

Screenshot of a svg
![_home_cdiesh_Downloads_image%20(42) svg (1)](https://user-images.githubusercontent.com/6511937/88706026-4c524a80-d0de-11ea-8bfb-a1dbe167af3e.png)

**Comment by cmdcolin** [comment]
[image.zip](https://github.com/GMOD/jbrowse-components/files/4990439/image.zip)
Actual svg

**Comment by cmdcolin** [comment]
Experimented with more SVG exporting with wiggle

![image (48)2](https://user-images.githubusercontent.com/6511937/89587065-d3a26b00-d80e-11ea-86ce-1713bbe057ad.png)

This actually uses d3 to generate the line path. See https://observablehq.com/@d3/d3-line for example how this can have a canvas or svg backend, no d3.select is used

It also exports using dynamic blocks instead of static blocks, which reduces "overplotting" in the generated svg where the features from neighboring plots generate the same feature. In our live instance we get overplotting and it generally doesn't affect anything but maybe mild non-pixel-perfect rendering, but for the outputted svg I figured achieving a better output would be good

Example screenshot of the svg
![image (49)](https://user-images.githubusercontent.com/6511937/89587891-7f988600-d810-11ea-9962-fe67c1776640.png)


Actual svg
[image (49).zip](https://github.com/GMOD/jbrowse-components/files/5038267/image.49.zip)

**Comment by cmdcolin** [comment]
Interesting note about using d3: that line is a single `<path>` svg. In order to have color change along the line it needs to be broken up into multiple segments which is doable but breaks the elegance a lil bit

**Comment by rbuels** [comment]
this probably depends on #811
