### ISSUE TITLE
Find way to share code between jbrowse-web and jbrowse-desktop

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#744]

**Comment by cmdcolin** [comment]
Aspects of code like sessionModelFactory, rpc methods, etc can diverge if not careful

**Comment by cmdcolin** [comment]
#737 made sessionmodelfactory an exact copy across each just for reference, they had started to diverge mildly (one particular bugfix perhaps was changing for(const view of self.views) to a self.views.forEach because this has closure over view in an async below it

**Comment by rbuels** [comment]
I had a look through what's duplicated, and yeah the biggest chunk of repeated code is the session model.  I think rather than sharing the session model, it might be good to make a couple of mixin/compose-in files that have the assembly management stuff and the connection management stuff, put those in core, and have the session models for the products use them.

**Comment by garrettjstevens** [comment]
Here's something we can use to detect duplicated code that might be able to be shared (`jscpd` is "JavaScript Copy Paste Detector"):
```bash
npx jscpd --ignore "**/node_modules/**,**/*.test.*,**/dist/**,**/test_data/**,**/build/**" --reporters html packages/
```

Sample output screenshot:
![image](https://user-images.githubusercontent.com/25592344/70933669-a263f900-1ff9-11ea-8ad4-7ba976475d6b.png)

**Comment by cmdcolin** [comment]
This will probably be addressed incrementally although it hasn't  been done yet

**Comment by rbuels** [comment]
Yeah this is pretty much getting done through a combination of 1.) moving
more code into the plugins by making more and more pluggable types, 2.)
moving shared things that are not plugins into core
