### ISSUE TITLE
add VCFInfo column type to spreadsheet view

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#788]
Add a VCFInfoString.js in spreadsheet-view ColumnDataTypes, which models the complex VCF info column and has some advanced filtering capabilities just for it.

**Comment by cmdcolin** [comment]
one method for this would be, instead of being a single specialized column, the initial parsing of the VCF will provide extra columns based on the union of the keys parsed from the INFO column. I added something like this for my SV hackathon

see https://cmdcolin.github.io/svxplorer/

the columns of the table are a union of keys parsed from the INFO field

**Comment by cmdcolin** [comment]
![image](https://github.com/GMOD/jbrowse-components/assets/6511937/ee53dbe3-50d7-49aa-ac08-d852d0783901)

**Comment by cmdcolin** [comment]
could be a separate feature request but note that the links are 'pre-populated' to open a set of tracks, which enables 'easier qc' of many variants
