### ISSUE TITLE
Use SVG instead of font icons

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/jbrowse-components#894]
Currently for our icons we use the material icon font for our icons. However, Material-UI suggests using SVG fonts whenever possible: https://material-ui.com/components/icons/#font-vs-svg-which-approach-to-use

We originally used font icons because we wanted users to be able to specify menu item icons in config files, which isn't possible with SVG (but with the icon font you could just specify a string).

Now that menus are not in the config, though, that reason no longer holds, so we should perhaps move to using SVG fonts instead. The link above explains some advantages of SVG, but some of the highlights for us might be:

* Smaller: Webpack should only bundle the icons we actually use, instead of the whole icon font.
* Plugins can easily use their own custom icons like this:

```js
<SvgIcon>
  <path d="M20 12l-1.41-1.41L13 16.17V4h-2v12.17l-5.58-5.59L4 12l8 8 8-8z" />
</SvgIcon>
```

* No "loading flicker" where the font hasn't loaded yet, so the icon doesn't appear properly. Especially noticeable on slower machines/connections. Example:

![image](https://user-images.githubusercontent.com/25592344/80029489-1597e300-84a4-11ea-8c83-6e41bb489a75.png)

**Comment by cmdcolin** [comment]
the https://www.npmjs.com/package/@material-ui/icons says that it includes all the official ones wrapped as svgicon, so just import these instead?

**Comment by garrettjstevens** [comment]
Yes, so in our codebase that would would look like

```js
import StarIcon from '@material-ui/icons/Star';

<StarIcon />
```

instead of 

```js
import Icon from '@material-ui/core/Icon';

<Icon>star</Icon>
```

**Comment by rbuels** [comment]
This sounds good to me

**Comment by cmdcolin** [comment]
what is the jbrequire strategy for this one? I think probably it's not the best to reexport all things, then it's just like might as well use the font. in absense of that, circular view for example would runtime depend on @material-ui/icons instead of peerDepend on it?

**Comment by rbuels** [comment]
I *think* webpacking a plugin bundle would only include the SVG of the icons they actually use, so probably just having plugins import it normally like @cmdcolin said would be fine

**Comment by cmdcolin** [comment]
that implies plugins are in change of "dependencies" including "@material-ui/icons". then they basically don't get it as a peerdependency, which can be a weird thing to have. we could re-export a small number of icons if we feel it is better for our ecosystem and then it could move back to a peerdependency. alternatively, jbrequire use the webfont as it is doing currently, while some core things use the svgicon since they cause more visible artefacts like in garretts screenshot

while this is just icons, it does point to an interesting phenomena where the plugins can't really use anything that is not in re-exports.  a similar analogy in jbrowse 1 is: plugins "can't use any dojo module that is not" used by the main jbrowse codebase (or at least, the is before the webpacking was put in place) unless they make a custom jbrowse build (which is always done after webpacking was put in place). but since jbowse 2 proposes to be more like jbrowse 1 pre-webpack-required-for-all-plugins, does this mean we want to load re-exports with all the material-ui widgets just to make sure plugins can use anything they want? or do they runtime depend on a potentially different material-ui version?

**Comment by rbuels** [comment]
Nothing will prevent plugins from importing anything they want. It's just that for *some* things that are also used by core, they will want to use a re-exported one so that we can be sure they are using the same version. The things that come to mind as critical for that are MST, material, and React, but there are probably some others

**Comment by cmdcolin** [comment]
I understand that, but I specifically point to material: if they want to use a custom material component, it may involve them runtime depending on material-ui and peerDependency on material-ui

**Comment by rbuels** [comment]
Oh I see. That’s not awesome, I can’t think of a way to ensure that they
will be using the same MUI as any JBrowse they install into in that case.
Do we think different versions of MUI might have problems coexisting?

**Comment by cmdcolin** [comment]
With something as simple as a SvgIcon, it might be ok to manually have multiple versions of that coexisting

Then we runtime depend on @material-ui/icons from plugins and other places

But for other things, it seems probably like we probably don't want to allow for multiple material-ui versions, and therefore, it will just sorta be a reality that users can't really use modules that aren't re-exported or do so at their peril

**Comment by garrettjstevens** [comment]
I can't think of any better options, either. At the very least we should make sure that @material-ui/core/SvgIcon is re-exported, and I think plugins runtime depending on @material-ui/icons will probably be fine. But short of us re-exporting all of @material-ui/core, people may just have to be really careful if they want to use a material-ui component that we don't. (Maybe we should try re-exporting all of @material-ui/core sometime, though, just to see how much bigger it actually makes our bundle)

**Comment by cmdcolin** [comment]
My understanding is that @material-ui/icons automatically wraps components in SvgIcon but otherwise ya

**Comment by garrettjstevens** [comment]
Yeah, I'm just saying to re-export it so plugins can easily make their own custom SVG icons.

**Comment by cmdcolin** [comment]
A small number of things still use Icon, notable Menu, but the majority rendered icons that are on the first paint will be svg instead of the weird thing like the first screenshot
