### ISSUE TITLE
LGV touchpad side scrolling is janky on OSX+Firefox

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse-components#959]
To reproduce:

* be running OS X with Firefox
* open an LGV
* open a track or two
* two-finger side-scroll in the LGV, doesn't respond very well

**Comment by cmdcolin** [comment]
This is a "speculative idea for optimization" and maybe should worth investigating but one thing frame we recalculate blocks, which seems like it is something that can be a limiting factor for slowness because it goes through the whole mobx machinery to do this and at that point it is hard to optimize

**Comment by cmdcolin** [comment]
Added #972  to try to address this a bit, room for improvement as far as rerendering is majority related to the RefNameAutocomplete and LocString box at least as far as the per frame work is concerned (other things can affect the perceived jank such as certain frames taking longer, but the average FPS improvements come from reducing rerenderings mostly

![Screenshot from 2020-05-30 19-35-25](https://user-images.githubusercontent.com/6511937/83341049-e8adcb80-a2ac-11ea-9612-573659058d5c.png)

**Comment by cmdcolin** [comment]
#973 also contributed to improvements, cross browser performance improvement should be noted (avoids "blinking" white blocks while scrolling)

**Comment by cmdcolin** [comment]
Some improvements were made. I know there are always gonna be more, it's hard to keep the frame rate up but reducing rerenders generally seems to help

One remaining thing I saw is that click and drag scrolling on the linear genome view produces double renders, a minor but noticeable issue

![Screenshot from 2020-06-01 20-13-43](https://user-images.githubusercontent.com/6511937/83468060-b2f21980-a449-11ea-95f5-5ee8ca821484.png)


They are related to the Header bar/OverviewScaleBar since turning the header off makes double rendering stop

It is confusing because wheel scrolling does not have the double renders though

I was looking at some possible modifications here that includes what I think might be refactorings related to the header bar https://github.com/GMOD/jbrowse-components/tree/reduce_click_and_drag_rerendering e.g. computed view for visibleLocStrings, etc.

**Comment by cmdcolin** [comment]
I think this can probably be closed now, optimizations that were generally applicable were made including the above click and drag one. If it continues to be an issue do re-open

**Comment by cmdcolin** [comment]
for posterity, general resource for scroll jank that goes beyond just reducing rerenders in react

http://jankfree.org/

**Comment by rbuels** [comment]
@peterkxie could you have a look at this and confirm that colin's optimizations took care of it?

**Comment by peterkxie** [comment]
still seeing some jankyness on macOS 10.15.4 and fresh install of firefox (77.0.1) on master
Loaded the NA Exome Track at 1:253473..286752

When two finger scrolling, it feels like it lags in the beginning and then finishes the scroll
Scrolls a little bit -> pauses for a second -> finishes rest of scroll

**Comment by cmdcolin** [comment]
Oh well.. hopefully some of the changes I made improve average performance on chrome, and I think firefox should have been moderately improved too. Looking at the difference between chrome and firefox tests is kind of interesting

-This is a performance trace from a short side scroll on Chrome

![www speedscope app_ (1)](https://user-images.githubusercontent.com/6511937/83689757-9d9dfc00-a5bd-11ea-97f9-0715744eca77.png)
If we look at a performance trace from chrome, the stack frames are very fast and close together


-This is a performance trace from a short side scroll on Firefox:

![www speedscope app_ (2)](https://user-images.githubusercontent.com/6511937/83689789-a7bffa80-a5bd-11ea-8261-53770782314c.png)
In firefox the frames are interrupted by layout, have generally some interesting differences that make it so that everything is not so tightly packed


Some notes:

- differences are not really related to the differences in offscreencanvas or anything like that, since these scrolling behavior differences happen with 0 tracks on the screen

-The differences are probably related to different JS and layouting behaviors, as seen in the stack trace

**Comment by cmdcolin** [comment]
I don't think there is any actionable todo here....I think probably close for now. Note that firefox has a variety of differences and we use normalize-wheel to standardize scrolling across from them, and in fact, has a larger pixelX delta

With this change

```
diff --git a/plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx b/p>
index 3496bf04b..e7ee7c7a7 100644
--- a/plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
+++ b/plugins/linear-genome-view/src/LinearGenomeView/components/TracksContainer.tsx
@@ -143,6 +143,7 @@ function TracksContainer({
         if (Math.abs(event.pixelX) > Math.abs(2 * event.pixelY)) {
           origEvent.preventDefault()
         }
+        console.log(event.pixelX)

```


On chrome, the output is variable size

```
7.7617106437683105
TracksContainer.tsx:146 17.075763702392578
TracksContainer.tsx:146 24.837472915649414
TracksContainer.tsx:146 4.657026290893555
TracksContainer.tsx:146 1.5523420572280884
TracksContainer.tsx:146 10.866394996643066
TracksContainer.tsx:146 3.1046841144561768

```

On firefox it is

```
40
40
40
40
40
40
40
```

It's just how it is afaik, if there are any concerns we can reopen but maybe close for now
