### ISSUE TITLE
Drawer widget improvements

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#98]
Currently, clicking 'X' in the track selector brings up a screen "Welcome to JBrowse" instead of a collapse functionality

**Comment by garrettjstevens** [comment]
That's the intended functionality, the "X" is meant to close the current widget so that the "default" widget is visible, but we haven't done anything with specifying a default drawer widget yet.

We actually need to talk about what to do if we want to hide the drawer, though. We decided to not worry about hiding it when I first developed it, but it still might be a good feature to have. So many of the actions are tied to the drawer, though, that we might still have to have the drawer open temporarily when you click on things.

**Comment by rbuels** [comment]
From a UI perspective, having the drawer go away with "X" is probably ideal. We would just need to work on smoothing out the animation.

**Comment by cmdcolin** [comment]
This might be overloading this issue but I will note that dragging to resize the drawer, at the moment, results in fairly choppy performance

**Comment by cmdcolin** [comment]
Reduce dependency on window.innerWidth in the root model
